// Generated by tools/mkucd.py from Unicode 16.0.0; do not edit.
#pragma once

#include "ucd.h"

extern const u8 UCD_REC_1[4352];
extern const u16 UCD_REC_2[6784];
extern const u16 UCD_REC_3[10720];
constexpr u32 UCD_REC_SHIFT1 = 3;
constexpr u32 UCD_REC_SHIFT2 = 5;
extern const UcdRec UCD_RECS[1318];
extern const UcdCase UCD_CASES[452];
extern const u32 UCD_EXT[747];
extern const f64 UCD_NUMBERS[144];
extern const u8 UCD_DEC_1[1088];
extern const u16 UCD_DEC_2[2688];
extern const u16 UCD_DEC_3[18832];
constexpr u32 UCD_DEC_SHIFT1 = 4;
constexpr u32 UCD_DEC_SHIFT2 = 6;
extern const u16 UCD_DEC[56765];
extern const u32 UCD_COMPOSE[4080];
extern const u32 UCD_OLD_UNASSIGNED[1292];
extern const UcdOld UCD_OLD_RECS[630];
extern const f64 UCD_OLD_NUMBERS[6];
extern const u32 UCD_OLD_NORM[10];
extern const Str UCD_ALGO_PREFIX[6];
constexpr u32 UCD_NAMED = 34137;
constexpr u32 UCD_WORDS = 13532;
constexpr u32 UCD_LONGEST_NAME = 88;
extern const u8 UCD_LEX[98306];
extern const u32 UCD_LEX_AT[846];
extern const u8 UCD_NAMES[221526];
extern const u32 UCD_NAMES_AT[1067];
extern const u32 UCD_NAME_RUNS[2148];
extern const u32 UCD_ALGO[57];
extern const u8 UCD_EXTRA_TEXT[15348];
extern const u32 UCD_ALIASES[1431];
extern const u32 UCD_SEQS[1844];
extern const u16 UCD_SEQ_UNITS[972];
