0 b'\n' b'' b'' b'' b'<~~>'
True True True True
b'`\n' True 0 7 b''
1 b'AA==\n' b'AA' b'AA======' b'00' b'<~!!~>'
True True True True
b'!````\n' True 3523407757 1792 b'00'
2 b'AAE=\n' b'AAE' b'AAAQ====' b'009' b'<~!!*~>'
True True True True
b'"``$`\n' True 920527465 24774 b'0001'
3 b'AAEC\n' b'AAEC' b'AAAQE===' b'009C' b'<~!!*-\n~>'
True True True True
b'#``$"\n' True 139757951 35556 b'000102'
4 b'AAECAw==\n' b'AAECAw' b'AAAQEAY=' b'009C6' b"<~!!*-'\n~>"
True True True True
b'$``$"`P``\n' True 2344191507 58529 b'000102-03'
5 b'AAECAwQ=\n' b'AAECAwQ' b'AAAQEAYE' b'009C61O' b'<~!!*-\'\n"9~>'
True True True True
b'%``$"`P0`\n' True 1364906956 23598 b'000102-0304'
7 b'AAECAwQFBg==\n' b'AAECAwQFBg' b'AAAQEAYEAUDA====' b'009C61O)~' b'<~!!*-\'\n"9eu~>'
True True True True
b'\'``$"`P0%!@``\n' True 2908228089 4429 b'000102-030405-06'
45 b'AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKiss\n' b'AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKiss' b'AAAQEAYEAUDAOCAJBIFQYDIOB4IBCEQTCQKRMFYYDENBWHA5DYPSAIJCEMSCKJRHFAUSUKZM' b'009C61O)~M2nh-c3=Iws5D^j+6crX17#SKH9337XAR!_nBqb&%C@Cr{EC' b'<~!!*-\'\n"9eu7#R\nLhG$k3[\nW&.oNg\'\nGVB"(`=\n52*$$(B\n+<_pR,U\nFcb-n-V\nr/-~>'
True True True True
b'M``$"`P0%!@<("0H+#`T.#Q`1$A,4%187&!D:&QP=\'A\\@(2(C)"4F)R@I*BLL\n' True 3619484613 49641 b'000102-030405-060708-090a0b-0c0d0e-0f1011-121314-151617-18191a-1b1c1d-1e1f20-212223-242526-272829-2a2b2c'
b'AAECAwQFBgcICQoLDA0ODxAREhMU\nFRYXGBkaGxwdHh8gISIjJCUmJygp\nKissLS4vMDEyMzQ1Njc4OTo7PD0+\nP0BBQkNERUZHSElKS0xNTk9QUVJT\nVFVWV1hZWltcXV5fYGFiY2RlZmdo\naWprbG1ub3BxcnN0dXZ3eHl6e3x9\nfn+AgYKDhIWGh4iJiouMjY6PkJGS\nk5SVlpeYmZqbnJ2en6ChoqOkpaan\nqKmqq6ytrq+wsbKztLW2t7i5uru8\nvb6/wMHCw8TFxsfIycrLzM3Oz9DR\n0tPU1dbX2Nna29zd3t/g4eLj5OXm\n5+jp6uvs7e7v8PHy8/T19vf4+fr7\n/P3+/1RoZSBxdWljayBicm93biBm\nb3g=\n'
b'hello_=3D_world_=09\nmore.\n=2E\n=00=11"3DUfw=88=99=AA=BB=CC=DD=EE=FF=00=11"3DUfw=88=99=AA=BB=CC=DD=EE=FF=00=\n=11"3DUfw=88=99=AA=BB=CC=DD=EE=FF=00=11"3DUfw=88=99=AA=BB=CC=DD=EE=FF=00=11=\n"3DUfw=88=99=AA=BB=CC=DD=EE=FF'
b'a=bc=ZZ d'
b'a' False Error Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4
b'a' True Error Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4
b'ab=' False Error Incorrect padding
b'ab=' True Error Incorrect padding
b'=ab' False Error Incorrect padding
b'=ab' True Error Leading padding not allowed
b'ab==c' False Error Incorrect padding
b'ab==c' True Error Excess data after padding
b'a@b=' False Error Incorrect padding
b'a@b=' True Error Only base64 data is allowed
b'abc=d' False b'i\xb7\x1d'
b'abc=d' True Error Excess data after padding
b'AB=' Error Incorrect padding
b'ABC=====' Error Invalid base32-encoded string: number of data characters (3) cannot be 1, 3, or 6 more than a multiple of 8
b'A' Error Invalid base32-encoded string: number of data characters (1) cannot be 1, 3, or 6 more than a multiple of 8
b'==' Error Leading padding not allowed
b'AB======C' Error Excess data after padding
b'z!' Error Ascii85 encoded byte sequences must end with b'~>'
b'!!!!!' Error Ascii85 encoded byte sequences must end with b'~>'
b'xyz' Error Ascii85 encoded byte sequences must end with b'~>'
b'~>' b''
b's8W-"~>' Error Ascii85 overflow
b'\xde\xad' b'\xbe\xef'
Error Odd number of hexadecimal digits
Error Non-hexadecimal digit found
ValueError string argument should contain only ASCII characters
(<class 'binascii.Error'>, <class 'ValueError'>, <class 'Exception'>, <class 'BaseException'>, <class 'object'>) binascii b'0123456789ABCDEFGHIJKLMNOPQRSTUV'
b'\xfb\xff\xbf' b'D1KG===='
899311407 01:0203:0405 7879-7a
a2b_base64() takes exactly 1 positional argument (2 given)
b'01000200'
