deque([0, 1, 2, 3, 4]) 5 0 4 [0, 1, 2, 3, 4] True False True False
4 0 deque([1, 2, 3])
deque([3, 1, 2])
deque([2, 3, 1])
deque([3, 1, 2])
deque([10, 9, 3, 1, 2, 7, 8]) 1 6 deque([10, 9, 3, 1, 2, 7, 8])
deque([10, 99, 9, 3, 1, 2, 8])
deque([8, 2, 1, 3, 9, 99, 10]) [10, 99, 9, 3, 1, 2, 8]
deque([-1, 2, 1, 3, 9, 99, 10])
deque([2, 1, 3, 9, 99, 10])
deque([]) 0
deque([3, 4, 5], maxlen=3) 3
deque([-1, 3, 4], maxlen=3) deque([3, 4], maxlen=2)
True True
True True
deque([1], maxlen=5) deque([])
deque(['a', 'b', 'c']) deque([0, 1, 2]) [2, 1]
50 49 0 [49, 48, 47]
24 25
defaultdict(<class 'list'>, {'a': [1, 2], 'b': [3]}) [1, 2] True <class 'list'> 2
{'h': 1, 'e': 1, 'l': 2, 'o': 1} [('e', 1), ('h', 1), ('l', 2), ('o', 1)]
True {'a': [1, 2], 'b': [3]} ['a', 'b'] False
KeyError 'x'
defaultdict(<class 'list'>, {'a': [1, 2], 'b': [3]}) True
OrderedDict({'a': 1, 'b': 2, 'c': 3}) ['a', 'b', 'c'] 2 3
['b', 'c', 'a']
['c', 'b', 'a']
('a', 1) ('c', 3) [('b', 2)]
False True True
{'a': 1, 'b': 2} 1 3 ['a', 'b', 'c']
OrderedDict({'c': 3}) 2 OrderedDict({'c': 3})
{'a': 2, 'b': 3, 'c': 1}
{'a': 3, 'b': 4, 'c': 1}
