5 3 12 3.5 3
1 1024 8 14 6
1024 128 -5 -5 -6
5 5.5 5.0 True False
ab abab 7 [1, 2]
True True True True True False
True True 7 2
3 True 2
1
2 {'a': 1, 'b': 2}
{'b': 2}
[1, 2, 3] [1, 2, 3]
[1, 2] [1, 1, 1]
Money(3) Money(7) Money(-5)
True False False
[Money(1), Money(2), Money(3)]
8 ('a', 'c')
5 [2, 3]
7 (7, 7)
3.0 7
HI cbt
2
[(1, 'a'), (2, 'b')]
[Money(1), Money(3)]
['a', 'b']
op.add(1, 'a') TypeError
op.itemgetter() TypeError
op.attrgetter(1) TypeError
op.index(1.5) TypeError
op.getitem([1], 9) IndexError
