CallableProxyType strC add radd 3 ('called', (1,)) [1, 2] 1 ('meth', 2) ('item', 5) True False
True True <class 'weakref.ProxyType'> <class 'weakref.CallableProxyType'>
True True True
ProxyType
unhashable type: 'weakref.ProxyType'
5 5 none True
False
True True
ReferenceError weakly-referenced object no longer exists
ReferenceError weakly-referenced object no longer exists
ReferenceError weakly-referenced object no longer exists
ReferenceError weakly-referenced object no longer exists
True
cannot create weak reference to 'int' object
cannot create weak reference to 'str' object
cannot create weak reference to 'NoneType' object
True True True
2
[2]
not a weakref
