True True
True True
True True
None None None None
False False False
False True True
False True True
True True True
True True False
True False True
2 1 3
True True 5
3 NotImplemented 6
-3 3 -4 2.5
True True True
[3, 2, 1] ['a']
True 'a' 1
[1] {} True False 
1 2 a
[9, 2, 3]
[2, 3]
1 made:z False 1
{'x': 2, 'y': 0} 0 {'x': 2, 'y': 0}
KeyError 'q'
True False True 4 49
True False 3 2 [3, 2, 1] [1, 2, 3, 4]
