'%c' 'Thu Feb 29 13:05:09 2024'
'%x' '02/29/24'
'%X' '13:05:09'
'%D' '02/29/24'
'%F' '2024-02-29'
'%T' '13:05:09'
'%R' '13:05'
'%r' '01:05:09 PM'
'%C' '20'
'%g' '24'
'%G' '2024'
'%V' '09'
'%u' '4'
'%U' '08'
'%W' '09'
'%k' '13'
'%l' ' 1'
'%e' '29'
'%P' 'P'
'%Q' 'Q'
'%Ey' '24'
'%Od' '29'
'%h' 'Feb'
'%n' '\n'
'%t' '\t'
'%%' '%'
'abc%' 'abc%'
'%' '%'
'%5Y' '5Y'
'%-d' '29'
'%_d' '29'
'%0e' '29'
'%v' '29-Feb-2024'
'%i' 'i'
'%N' 'N'
'%L' 'L'
'%E' 'E'
'%O' 'O'
'é%Y€' 'é2024€'
'-005 05 -0 -005 05' '12345 45' '0099'
time.struct_time(tm_year=1970, tm_mon=1, tm_mday=1, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=1, tm_isdst=0) UTC 0
ValueError Invalid value NaN (not a number)
OverflowError timestamp out of range for platform time_t
OverflowError timestamp out of range for platform time_t
TypeError must be real number, not str
time.struct_time(tm_year=1969, tm_mon=12, tm_mday=31, tm_hour=23, tm_min=59, tm_sec=58, tm_wday=2, tm_yday=365, tm_isdst=0)
TypeError asctime(): illegal time tuple argument
TypeError Tuple or struct_time argument required
ValueError month out of range
ValueError day of week out of range
Mon Jan  1 00:00:00 2024
Mon Jan  1 00:00:00 2024
TypeError 'float' object cannot be interpreted as an integer
time.struct_time(tm_year=1, tm_mon=2, tm_mday=3, tm_hour=4, tm_min=5, tm_sec=6, tm_wday=7, tm_yday=8, tm_isdst=9) X
time.struct_time() takes an at least 9-sequence (2-sequence given)
time.struct_time() takes an at most 11-sequence (12-sequence given)
time.struct_time(tm_year=2024, tm_mon=3, tm_mday=4, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=64, tm_isdst=-1) time.struct_time(tm_year=2024, tm_mon=2, tm_mday=29, tm_hour=13, tm_min=5, tm_sec=9, tm_wday=3, tm_yday=60, tm_isdst=-1)
2020-53-5 20 00 00 001 Fri time.struct_time(tm_year=2021, tm_mon=1, tm_mday=1, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=4, tm_yday=1, tm_isdst=0)
2020-53-4 20 52 52 366 Thu time.struct_time(tm_year=2020, tm_mon=12, tm_mday=31, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=366, tm_isdst=0)
2026-53-7 26 01 00 003 Sun time.struct_time(tm_year=2027, tm_mon=1, tm_mday=3, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=6, tm_yday=3, tm_isdst=0)
2026-53-1 26 52 52 362 Mon time.struct_time(tm_year=2026, tm_mon=12, tm_mday=28, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=362, tm_isdst=0)
2004-53-1 04 52 52 362 Mon time.struct_time(tm_year=2004, tm_mon=12, tm_mday=27, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=362, tm_isdst=0)
2004-53-7 04 01 00 002 Sun time.struct_time(tm_year=2005, tm_mon=1, tm_mday=2, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=6, tm_yday=2, tm_isdst=0)
2009-53-7 09 01 00 003 Sun time.struct_time(tm_year=2010, tm_mon=1, tm_mday=3, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=6, tm_yday=3, tm_isdst=0)
ValueError Invalid value NaN (not a number)
TypeError must be real number, not str
ValueError unknown clock
OSError [Errno 22] Invalid argument
11 <class 'float'> time.struct_time(tm_year=2286, tm_mon=11, tm_mday=20, tm_hour=17, tm_min=46, tm_sec=40, tm_wday=5, tm_yday=324, tm_isdst=0) -1199
   February 2024
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29
 True 3 (calendar.WEDNESDAY, 28)
