Module
  body:
    Expr @1:0-1:3
      value:
        Call @1:0-1:3
          func:
            Name f @1:0-1:1
          args: []
          keywords: []
    Expr @2:0-2:4
      value:
        Call @2:0-2:4
          func:
            Name f @2:0-2:1
          args:
            Constant 1 @2:2-2:3
          keywords: []
    Expr @3:0-3:7
      value:
        Call @3:0-3:7
          func:
            Name f @3:0-3:1
          args:
            Constant 1 @3:2-3:3
            Constant 2 @3:5-3:6
          keywords: []
    Expr @4:0-4:6
      value:
        Call @4:0-4:6
          func:
            Name f @4:0-4:1
          args: []
          keywords:
            Keyword a @4:2-4:5
              value:
                Constant 1 @4:4-4:5
    Expr @5:0-5:9
      value:
        Call @5:0-5:9
          func:
            Name f @5:0-5:1
          args:
            Constant 1 @5:2-5:3
          keywords:
            Keyword a @5:5-5:8
              value:
                Constant 2 @5:7-5:8
    Expr @6:0-6:5
      value:
        Call @6:0-6:5
          func:
            Name f @6:0-6:1
          args:
            Starred @6:2-6:4
              value:
                Name a @6:3-6:4
          keywords: []
    Expr @7:0-7:6
      value:
        Call @7:0-7:6
          func:
            Name f @7:0-7:1
          args: []
          keywords:
            Keyword ** @7:2-7:5
              value:
                Name k @7:4-7:5
    Expr @8:0-8:10
      value:
        Call @8:0-8:10
          func:
            Name f @8:0-8:1
          args:
            Starred @8:2-8:4
              value:
                Name a @8:3-8:4
          keywords:
            Keyword ** @8:6-8:9
              value:
                Name k @8:8-8:9
    Expr @9:0-9:15
      value:
        Call @9:0-9:15
          func:
            Name f @9:0-9:1
          args:
            GeneratorExp @9:1-9:15
              elt:
                Name x @9:2-9:3
              generators:
                Comprehen
                  target:
                    Name x @9:8-9:9
                  iter:
                    Name y @9:13-9:14
                  ifs: []
          keywords: []
    Expr @10:0-10:10
      value:
        Call @10:0-10:10
          func:
            Name f @10:0-10:1
          args:
            Call @10:2-10:9
              func:
                Name g @10:2-10:3
              args:
                Call @10:4-10:8
                  func:
                    Name h @10:4-10:5
                  args:
                    Constant 1 @10:6-10:7
                  keywords: []
              keywords: []
          keywords: []
    Expr @11:0-11:7
      value:
        Call @11:0-11:7
          func:
            Attribute c @11:0-11:5
              value:
                Attribute b @11:0-11:3
                  value:
                    Name a @11:0-11:1
          args: []
          keywords: []
    Expr @12:0-12:7
      value:
        Subscript @12:0-12:7
          value:
            Subscript @12:0-12:4
              value:
                Name a @12:0-12:1
              slice:
                Constant 0 @12:2-12:3
          slice:
            Constant 1 @12:5-12:6
    Expr @13:0-13:12
      value:
        Subscript @13:0-13:12
          value:
            Call @13:0-13:9
              func:
                Attribute b @13:0-13:6
                  value:
                    Subscript @13:0-13:4
                      value:
                        Name a @13:0-13:1
                      slice:
                        Constant 0 @13:2-13:3
              args:
                Constant 1 @13:7-13:8
              keywords: []
          slice:
            Constant 2 @13:10-13:11
    Expr @14:0-14:36
      value:
        Call @14:0-14:36
          func:
            Attribute method @14:0-14:10
              value:
                Name obj @14:0-14:3
          args:
            Starred @14:11-14:16
              value:
                Name args @14:12-14:16
          keywords:
            Keyword key @14:18-14:27
              value:
                Name value @14:22-14:27
            Keyword ** @14:29-14:35
              value:
                Name rest @14:31-14:35
