Module
  body:
    Expr @1:0-1:3
      value:
        JoinedStr @1:0-1:3
          values: []
    Expr @2:0-2:8
      value:
        JoinedStr @2:0-2:8
          values:
            Constant 'plain'
    Expr @3:0-3:6
      value:
        JoinedStr @3:0-3:6
          values:
            FormattedValue -
              value:
                Name x
              format_spec: -
    Expr @4:0-4:8
      value:
        JoinedStr @4:0-4:8
          values:
            Constant 'a'
            FormattedValue -
              value:
                Name x
              format_spec: -
            Constant 'b'
    Expr @5:0-5:8
      value:
        JoinedStr @5:0-5:8
          values:
            FormattedValue r
              value:
                Name x
              format_spec: -
    Expr @6:0-6:8
      value:
        JoinedStr @6:0-6:8
          values:
            FormattedValue s
              value:
                Name x
              format_spec: -
    Expr @7:0-7:8
      value:
        JoinedStr @7:0-7:8
          values:
            FormattedValue a
              value:
                Name x
              format_spec: -
    Expr @8:0-8:10
      value:
        JoinedStr @8:0-8:10
          values:
            FormattedValue -
              value:
                Name x
              format_spec:
                JoinedStr
                  values:
                    Constant '>10'
    Expr @9:0-9:16
      value:
        JoinedStr @9:0-9:16
          values:
            FormattedValue -
              value:
                Name x
              format_spec:
                JoinedStr
                  values:
                    Constant '>'
                    FormattedValue -
                      value:
                        Name w
                      format_spec: -
                    Constant '.'
                    FormattedValue -
                      value:
                        Name p
                      format_spec: -
                    Constant 'f'
    Expr @10:0-10:7
      value:
        JoinedStr @10:0-10:7
          values:
            FormattedValue -
              value:
                Name x
              format_spec:
                JoinedStr
                  values: []
    Expr @11:0-11:7
      value:
        JoinedStr @11:0-11:7
          values:
            Constant 'x='
            FormattedValue r
              value:
                Name x
              format_spec: -
    Expr @12:0-12:9
      value:
        JoinedStr @12:0-12:9
          values:
            Constant 'x = '
            FormattedValue r
              value:
                Name x
              format_spec: -
    Expr @13:0-13:9
      value:
        JoinedStr @13:0-13:9
          values:
            Constant 'x+1='
            FormattedValue r
              value:
                BinOp +
                  left:
                    Name x
                  right:
                    Constant 1
              format_spec: -
    Expr @14:0-14:14
      value:
        JoinedStr @14:0-14:14
          values:
            Constant '{literal}'
    Expr @15:0-15:23
      value:
        JoinedStr @15:0-15:23
          values:
            Constant 'before'
            FormattedValue -
              value:
                Name x
              format_spec: -
            Constant 'after'
    Expr @16:0-16:9
      value:
        JoinedStr @16:0-16:9
          values:
            Constant 'ab'
    Expr @17:0-17:11
      value:
        JoinedStr @17:0-17:11
          values:
            FormattedValue -
              value:
                Subscript
                  value:
                    Name d
                  slice:
                    Constant 'k'
              format_spec: -
    Expr @18:0-18:12
      value:
        JoinedStr @18:0-18:12
          values:
            FormattedValue -
              value:
                BinOp +
                  left:
                    Name x
                  right:
                    Constant 1
              format_spec: -
    Expr @19:0-19:11
      value:
        JoinedStr @19:0-19:11
          values:
            FormattedValue -
              value:
                Tuple
                  elts:
                    Constant 1
                    Constant 2
              format_spec: -
    Expr @20:0-20:19
      value:
        JoinedStr @20:0-20:19
          values:
            FormattedValue -
              value:
                ListComp
                  elt:
                    Name i
                  generators:
                    Comprehen
                      target:
                        Name i
                      iter:
                        Name y
                      ifs: []
              format_spec: -
    Expr @21:0-21:11
      value:
        JoinedStr @21:0-21:11
          values:
            FormattedValue -
              value:
                JoinedStr
                  values:
                    FormattedValue -
                      value:
                        Name x
                      format_spec: -
              format_spec: -
