Module
  body:
    FunctionDef f @1:0-5:15
      args:
        Arguments
          posonly: []
          args: []
          vararg: -
          kwonly: []
          kw_defaults: []
          kwarg: -
          defaults: []
      body:
        Expr @2:4-2:9
          value:
            Yield @2:4-2:9
              value: -
        Expr @3:4-3:11
          value:
            Yield @3:4-3:11
              value:
                Constant 1 @3:10-3:11
        Expr @4:4-4:18
          value:
            YieldFrom @4:4-4:18
              value:
                Call @4:15-4:18
                  func:
                    Name g @4:15-4:16
                  args: []
                  keywords: []
        Assign @5:4-5:15
          targets:
            Name x @5:4-5:5
          value:
            Yield @5:8-5:15
              value:
                Constant 2 @5:14-5:15
      decorators: []
      returns: -
    FunctionDef h @7:0-8:18
      args:
        Arguments
          posonly: []
          args: []
          vararg: -
          kwonly: []
          kw_defaults: []
          kwarg: -
          defaults: []
      body:
        Return @8:4-8:18
          value:
            Yield @8:12-8:17
              value: -
      decorators: []
      returns: -
