Module
  body:
    FunctionDef f @1:0-1:17
      args:
        Arguments
          posonly: []
          args:
            Arg x @1:9-1:10
              annotation: -
          vararg: -
          kwonly: []
          kw_defaults: []
          kwarg: -
          defaults: []
      body:
        Pass @1:13-1:17
      decorators: []
      returns: -
      type_params:
        TypeVar T @1:6-1:7
          bound: -
          default: -
    AsyncFunctionDef g @2:0-2:49
      args:
        Arguments
          posonly: []
          args: []
          vararg:
            Arg a @2:31-2:37
              annotation:
                Starred @2:34-2:37
                  value:
                    Name Ts @2:35-2:37
          kwonly: []
          kw_defaults: []
          kwarg:
            Arg k @2:41-2:42
              annotation: -
          defaults: []
      body:
        Pass @2:45-2:49
      decorators: []
      returns: -
      type_params:
        TypeVar T @2:12-2:18
          bound:
            Name int @2:15-2:18
          default: -
        TypeVarTuple Ts @2:20-2:23
          default: -
        ParamSpec P @2:25-2:28
          default: -
    ClassDef C @3:0-4:36
      bases:
        Name Base @3:54-3:58
      keywords:
        Keyword metaclass @3:60-3:71
          value:
            Name M @3:70-3:71
      body:
        FunctionDef m @4:4-4:36
          args:
            Arguments
              posonly: []
              args:
                Arg self @4:25-4:29
                  annotation: -
              vararg: -
              kwonly: []
              kw_defaults: []
              kwarg: -
              defaults: []
          body:
            Pass @4:32-4:36
          decorators: []
          returns: -
          type_params:
            TypeVar U @4:10-4:23
              bound:
                Tuple @4:13-4:23
                  elts:
                    Name int @4:14-4:17
                    Name str @4:19-4:22
              default: -
      decorators: []
      type_params:
        TypeVar T @3:8-3:15
          bound: -
          default:
            Name int @3:12-3:15
        TypeVarTuple Ts @3:17-3:34
          default:
            Starred @3:23-3:34
              value:
                Subscript @3:24-3:34
                  value:
                    Name tuple @3:24-3:29
                  slice:
                    Name int @3:30-3:33
        ParamSpec P @3:36-3:52
          default:
            List @3:42-3:52
              elts:
                Name int @3:43-3:46
                Name str @3:48-3:51
    ClassDef D @6:0-6:16
      bases: []
      keywords: []
      body:
        Pass @6:12-6:16
      decorators:
        Name deco @5:1-5:5
      type_params:
        TypeVar T @6:8-6:9
          bound: -
          default: -
    TypeAlias @7:0-7:12
      name:
        Name A @7:5-7:6
      type_params: []
      value:
        Name int @7:9-7:12
    TypeAlias @8:0-8:30
      name:
        Name B @8:5-8:6
      type_params:
        TypeVar K @8:7-8:8
          bound: -
          default: -
        TypeVar V @8:10-8:16
          bound:
            Name str @8:13-8:16
          default: -
      value:
        Subscript @8:20-8:30
          value:
            Name dict @8:20-8:24
          slice:
            Tuple @8:25-8:29
              elts:
                Name K @8:25-8:26
                Name V @8:28-8:29
    Assign @9:0-9:8
      targets:
        Name type @9:0-9:4
      value:
        Constant 1 @9:7-9:8
    Assign @10:0-10:11
      targets:
        Subscript @10:0-10:7
          value:
            Name type @10:0-10:4
          slice:
            Name x @10:5-10:6
      value:
        Constant 2 @10:10-10:11
    Assign @11:0-11:10
      targets:
        Attribute x @11:0-11:6
          value:
            Name type @11:0-11:4
      value:
        Constant 3 @11:9-11:10
    Expr @12:0-12:11
      value:
        Call @12:0-12:11
          func:
            Name print @12:0-12:5
          args:
            Name type @12:6-12:10
          keywords: []
