Module
  body:
    Assign @1:0-1:13
      targets:
        Name a @1:0-1:1
      value:
        BinOp + @1:4-1:13
          left:
            Constant 1 @1:4-1:5
          right:
            BinOp * @1:8-1:13
              left:
                Constant 2 @1:8-1:9
              right:
                Constant 3 @1:12-1:13
    Assign @2:0-2:15
      targets:
        Name b @2:0-2:1
      value:
        BinOp * @2:4-2:15
          left:
            BinOp + @2:5-2:10
              left:
                Constant 1 @2:5-2:6
              right:
                Constant 2 @2:9-2:10
          right:
            Constant 3 @2:14-2:15
    Assign @3:0-3:15
      targets:
        Name c @3:0-3:1
      value:
        BinOp ** @3:4-3:15
          left:
            Constant 2 @3:4-3:5
          right:
            BinOp ** @3:9-3:15
              left:
                Constant 3 @3:9-3:10
              right:
                Constant 4 @3:14-3:15
    Assign @4:0-4:11
      targets:
        Name d @4:0-4:1
      value:
        UnaryOp - @4:4-4:11
          operand:
            BinOp ** @4:5-4:11
              left:
                Constant 2 @4:5-4:6
              right:
                Constant 2 @4:10-4:11
    Assign @5:0-5:13
      targets:
        Name e @5:0-5:1
      value:
        BinOp ** @5:4-5:13
          left:
            UnaryOp - @5:5-5:7
              operand:
                Constant 2 @5:6-5:7
          right:
            Constant 2 @5:12-5:13
    Assign @6:0-6:14
      targets:
        Name f @6:0-6:1
      value:
        UnaryOp not @6:4-6:14
          operand:
            Compare @6:8-6:14
              left:
                Name a @6:8-6:9
              ops:
                CmpOp ==
                  operand:
                    Name b @6:13-6:14
    Assign @7:0-7:16
      targets:
        Name g @7:0-7:1
      value:
        BoolOp or @7:4-7:16
          values:
            Name a @7:4-7:5
            BoolOp and @7:9-7:16
              values:
                Name b @7:9-7:10
                Name c @7:15-7:16
    Assign @8:0-8:17
      targets:
        Name h @8:0-8:1
      value:
        BinOp | @8:4-8:17
          left:
            Name a @8:4-8:5
          right:
            BinOp ^ @8:8-8:17
              left:
                Name b @8:8-8:9
              right:
                BinOp & @8:12-8:17
                  left:
                    Name c @8:12-8:13
                  right:
                    Name d @8:16-8:17
    Assign @9:0-9:19
      targets:
        Name i @9:0-9:1
      value:
        BinOp | @9:4-9:19
          left:
            BinOp << @9:4-9:10
              left:
                Name a @9:4-9:5
              right:
                Constant 1 @9:9-9:10
          right:
            BinOp >> @9:13-9:19
              left:
                Name b @9:13-9:14
              right:
                Constant 2 @9:18-9:19
    Assign @10:0-10:16
      targets:
        Name j @10:0-10:1
      value:
        BinOp - @10:4-10:16
          left:
            BinOp + @10:4-10:11
              left:
                UnaryOp ~ @10:4-10:6
                  operand:
                    Name a @10:5-10:6
              right:
                UnaryOp - @10:9-10:11
                  operand:
                    Name b @10:10-10:11
          right:
            UnaryOp + @10:14-10:16
              operand:
                Name c @10:15-10:16
    Assign @11:0-11:17
      targets:
        Name k @11:0-11:1
      value:
        Compare @11:4-11:17
          left:
            Name a @11:4-11:5
          ops:
            CmpOp <
              operand:
                Name b @11:8-11:9
            CmpOp <
              operand:
                Name c @11:12-11:13
            CmpOp <
              operand:
                Name d @11:16-11:17
    Assign @12:0-12:29
      targets:
        Name m @12:0-12:1
      value:
        IfExp @12:4-12:29
          test:
            Name b @12:9-12:10
          body:
            Name a @12:4-12:5
          orelse:
            IfExp @12:16-12:29
              test:
                Name d @12:21-12:22
              body:
                Name c @12:16-12:17
              orelse:
                Name e @12:28-12:29
    Assign @13:0-13:21
      targets:
        Name n @13:0-13:1
      value:
        Lambda @13:4-13:21
          args:
            Arguments
              posonly: []
              args: []
              vararg: -
              kwonly: []
              kw_defaults: []
              kwarg: -
              defaults: []
          body:
            Lambda @13:12-13:21
              args:
                Arguments
                  posonly: []
                  args: []
                  vararg: -
                  kwonly: []
                  kw_defaults: []
                  kwarg: -
                  defaults: []
              body:
                Constant 1 @13:20-13:21
    Assign @14:0-14:15
      targets:
        Name o @14:0-14:1
      value:
        Attribute c @14:4-14:15
          value:
            Call @14:4-14:13
              func:
                Subscript @14:4-14:10
                  value:
                    Attribute b @14:4-14:7
                      value:
                        Name a @14:4-14:5
                  slice:
                    Constant 0 @14:8-14:9
              args:
                Constant 1 @14:11-14:12
              keywords: []
