Module
  body:
    Expr @1:0-1:4
      value:
        Subscript @1:0-1:4
          value:
            Name a @1:0-1:1
          slice:
            Constant 1 @1:2-1:3
    Expr @2:0-2:4
      value:
        Subscript @2:0-2:4
          value:
            Name a @2:0-2:1
          slice:
            Slice @2:2-2:3
              lower: -
              upper: -
              step: -
    Expr @3:0-3:5
      value:
        Subscript @3:0-3:5
          value:
            Name a @3:0-3:1
          slice:
            Slice @3:2-3:4
              lower:
                Constant 1 @3:2-3:3
              upper: -
              step: -
    Expr @4:0-4:5
      value:
        Subscript @4:0-4:5
          value:
            Name a @4:0-4:1
          slice:
            Slice @4:2-4:4
              lower: -
              upper:
                Constant 2 @4:3-4:4
              step: -
    Expr @5:0-5:6
      value:
        Subscript @5:0-5:6
          value:
            Name a @5:0-5:1
          slice:
            Slice @5:2-5:5
              lower:
                Constant 1 @5:2-5:3
              upper:
                Constant 2 @5:4-5:5
              step: -
    Expr @6:0-6:6
      value:
        Subscript @6:0-6:6
          value:
            Name a @6:0-6:1
          slice:
            Slice @6:2-6:5
              lower: -
              upper: -
              step:
                Constant 2 @6:4-6:5
    Expr @7:0-7:8
      value:
        Subscript @7:0-7:8
          value:
            Name a @7:0-7:1
          slice:
            Slice @7:2-7:7
              lower:
                Constant 1 @7:2-7:3
              upper:
                Constant 2 @7:4-7:5
              step:
                Constant 3 @7:6-7:7
    Expr @8:0-8:7
      value:
        Subscript @8:0-8:7
          value:
            Name a @8:0-8:1
          slice:
            Slice @8:2-8:6
              lower: -
              upper: -
              step:
                UnaryOp - @8:4-8:6
                  operand:
                    Constant 1 @8:5-8:6
    Expr @9:0-9:7
      value:
        Subscript @9:0-9:7
          value:
            Name a @9:0-9:1
          slice:
            Tuple @9:2-9:6
              elts:
                Name x @9:2-9:3
                Name y @9:5-9:6
    Expr @10:0-10:9
      value:
        Subscript @10:0-10:9
          value:
            Name a @10:0-10:1
          slice:
            Tuple @10:2-10:8
              elts:
                Slice @10:2-10:5
                  lower:
                    Constant 1 @10:2-10:3
                  upper:
                    Constant 2 @10:4-10:5
                  step: -
                Constant 3 @10:7-10:8
    Expr @11:0-11:6
      value:
        Subscript @11:0-11:6
          value:
            Name a @11:0-11:1
          slice:
            Constant Ellipsis @11:2-11:5
