Module
  body:
    Import @1:0-1:9
      names:
        Alias os @1:7-1:9
    Import @2:0-2:19
      names:
        Alias os.path as p @2:7-2:19
    ImportFrom - level=1 @3:0-3:15
      names:
        Alias x @3:14-3:15
    ImportFrom pkg.mod level=2 @4:0-4:31
      names:
        Alias a as b @4:22-4:28
        Alias c @4:30-4:31
    ImportFrom x level=0 @5:0-5:15
      names:
        Alias * @5:14-5:15
    FunctionDef f @7:0-13:12
      args:
        Arguments
          posonly: []
          args:
            Arg a @7:6-7:7
              annotation: -
            Arg b @7:9-7:10
              annotation: -
          vararg:
            Arg args @7:15-7:19
              annotation: -
          kwonly:
            Arg c @7:21-7:22
              annotation: -
            Arg d @7:24-7:25
              annotation: -
          kw_defaults:
            -
            Constant 2 @7:26-7:27
          kwarg:
            Arg kw @7:31-7:33
              annotation: -
          defaults:
            Constant 1 @7:11-7:12
      body:
        Global @8:4-8:12
          names:
            Name g
        AnnAssign simple @9:4-9:14
          target:
            Name x @9:4-9:5
          annotation:
            Name int @9:7-9:10
          value:
            Constant 1 @9:13-9:14
        AnnAssign simple @10:4-10:10
          target:
            Name y @10:4-10:5
          annotation:
            Name int @10:7-10:10
          value: -
        AugAssign += @11:4-11:10
          target:
            Name x @11:4-11:5
          value:
            Constant 1 @11:9-11:10
        Delete @12:4-12:9
          targets:
            Name x @12:8-12:9
        Return @13:4-13:12
          value:
            Name a @13:11-13:12
      decorators: []
      returns:
        Name int @7:38-7:41
    ClassDef C @17:0-19:12
      bases:
        Name Base @17:8-17:12
      keywords:
        Keyword metaclass @17:14-17:25
          value:
            Name M @17:24-17:25
        Keyword ** @17:27-17:31
          value:
            Name kw @17:29-17:31
      body:
        FunctionDef m @18:4-19:12
          args:
            Arguments
              posonly: []
              args:
                Arg self @18:10-18:14
                  annotation: -
              vararg: -
              kwonly: []
              kw_defaults: []
              kwarg: -
              defaults: []
          body:
            Pass @19:8-19:12
          decorators: []
          returns: -
      decorators:
        Name deco @15:1-15:5
        Call @16:1-16:12
          func:
            Attribute deco @16:1-16:9
              value:
                Name mod @16:1-16:4
          args:
            Constant 1 @16:10-16:11
          keywords: []
    AsyncFunctionDef g2 @21:0-26:12
      args:
        Arguments
          posonly: []
          args: []
          vararg: -
          kwonly: []
          kw_defaults: []
          kwarg: -
          defaults: []
      body:
        Expr @22:4-22:13
          value:
            Await @22:4-22:13
              value:
                Call @22:10-22:13
                  func:
                    Name h @22:10-22:11
                  args: []
                  keywords: []
        AsyncWith @23:4-24:12
          items:
            WithItem
              context:
                Name a @23:15-23:16
              vars:
                Name b @23:20-23:21
          body:
            Pass @24:8-24:12
        AsyncFor @25:4-26:12
          target:
            Name i @25:14-25:15
          iter:
            Name c @25:19-25:20
          body:
            Pass @26:8-26:12
          orelse: []
      decorators: []
      returns: -
    For @28:0-31:8
      target:
        Name i @28:4-28:5
      iter:
        Call @28:9-28:17
          func:
            Name range @28:9-28:14
          args:
            Constant 3 @28:15-28:16
          keywords: []
      body:
        Continue @29:4-29:12
      orelse:
        Pass @31:4-31:8
    While @33:0-36:8
      test:
        Constant True @33:6-33:10
      body:
        Break @34:4-34:9
      orelse:
        Pass @36:4-36:8
    Try @38:0-47:8
      body:
        Pass @39:4-39:8
      handlers:
        ExceptHandler e @40:0-41:9
          type:
            Name ValueError @40:7-40:17
          body:
            Raise @41:4-41:9
              exc: -
              cause: -
        ExceptHandler @42:0-43:18
          type:
            Tuple @42:7-42:28
              elts:
                Name TypeError @42:8-42:17
                Name KeyError @42:19-42:27
          body:
            Raise @43:4-43:18
              exc:
                Name X @43:10-43:11
              cause:
                Name Y @43:17-43:18
      orelse:
        Pass @45:4-45:8
      finalbody:
        Pass @47:4-47:8
    With @49:0-50:8
      items:
        WithItem
          context:
            Call @49:5-49:14
              func:
                Name open @49:5-49:9
              args:
                Constant 'a' @49:10-49:13
              keywords: []
          vars:
            Name f @49:18-49:19
        WithItem
          context:
            Call @49:21-49:30
              func:
                Name open @49:21-49:25
              args:
                Constant 'b' @49:26-49:29
              keywords: []
          vars: -
      body:
        Pass @50:4-50:8
    If @52:0-57:8
      test:
        Name a @52:3-52:4
      body:
        Pass @53:4-53:8
      orelse:
        If @54:0-57:8
          test:
            Name b @54:5-54:6
          body:
            Pass @55:4-55:8
          orelse:
            Pass @57:4-57:8
    Assert @59:0-59:15
      test:
        Name a @59:7-59:8
      msg:
        Constant 'msg' @59:10-59:15
    Assign @60:0-60:9
      targets:
        Name a @60:0-60:1
        Name b @60:4-60:5
      value:
        Name c @60:8-60:9
    Assign @61:0-61:11
      targets:
        Tuple @61:0-61:4
          elts:
            Name a @61:0-61:1
            Name b @61:3-61:4
      value:
        Tuple @61:7-61:11
          elts:
            Name b @61:7-61:8
            Name a @61:10-61:11
    Assign @62:0-62:13
      targets:
        Tuple @62:0-62:9
          elts:
            Tuple @62:0-62:6
              elts:
                Name a @62:1-62:2
                Name b @62:4-62:5
            Name c @62:8-62:9
      value:
        Name x @62:12-62:13
    Assign @63:0-63:10
      targets:
        List @63:0-63:6
          elts:
            Name a @63:1-63:2
            Name b @63:4-63:5
      value:
        Name y @63:9-63:10
    Expr @64:0-64:1
      value:
        Name a @64:0-64:1
    Expr @64:3-64:4
      value:
        Name b @64:3-64:4
    If @65:0-65:10
      test:
        Name a @65:3-65:4
      body:
        Expr @65:6-65:7
          value:
            Name b @65:6-65:7
        Expr @65:9-65:10
          value:
            Name c @65:9-65:10
      orelse: []
