Module
  body:
    TryStar @1:0-10:8
      body:
        Pass @2:4-2:8
      handlers:
        ExceptHandler e @3:0-4:8
          type:
            Name ValueError @3:8-3:18
          body:
            Pass @4:4-4:8
        ExceptHandler @5:0-6:8
          type:
            Tuple @5:8-5:29
              elts:
                Name TypeError @5:9-5:18
                Name KeyError @5:20-5:28
          body:
            Pass @6:4-6:8
      orelse:
        Pass @8:4-8:8
      finalbody:
        Pass @10:4-10:8
    Try @11:0-14:8
      body:
        Pass @12:4-12:8
      handlers:
        ExceptHandler @13:0-14:8
          type:
            Tuple @13:7-13:28
              elts:
                Name ValueError @13:7-13:17
                Name TypeError @13:19-13:28
          body:
            Pass @14:4-14:8
      orelse: []
      finalbody: []
