Module
  body:
    Expr @1:0-1:8
      value:
        TemplateStr @1:0-1:8
          values:
            Constant 'a'
            Interpolation -
              value:
                Name x
              str:
                Constant 'x'
              format_spec: -
            Constant 'b'
    Expr @2:0-2:25
      value:
        TemplateStr @2:0-2:25
          values:
            Constant 'x='
            Interpolation r
              value:
                Name x
              str:
                Constant 'x'
              format_spec: -
            Constant ' y = '
            Interpolation s
              value:
                Name y
              str:
                Constant ' y'
              format_spec:
                JoinedStr
                  values:
                    Constant '>'
                    FormattedValue -
                      value:
                        Name w
                      format_spec: -
    Expr @3:0-3:28
      value:
        TemplateStr @3:0-3:28
          values:
            Interpolation -
              value:
                Name x
              str:
                Constant 'x'
              format_spec:
                JoinedStr
                  values:
                    FormattedValue -
                      value:
                        Name y
                      format_spec: -
                    Constant '.'
                    FormattedValue -
                      value:
                        Name z
                      format_spec: -
            Constant '\\n'
            Interpolation -
              value:
                Name x
              str:
                Constant 'x'
              format_spec: -
    Expr @4:0-5:2
      value:
        TemplateStr @4:0-5:2
          values:
            Interpolation -
              value:
                BinOp +
                  left:
                    Name x
                  right:
                    Constant 1
              str:
                Constant ' x + 1'
              format_spec: -
    Expr @6:0-7:5
      value:
        TemplateStr @6:0-7:5
          values:
            Constant 'x\n='
            Interpolation r
              value:
                Name x
              str:
                Constant 'x'
              format_spec: -
    Expr @8:0-8:13
      value:
        TemplateStr @8:0-8:13
          values:
            Interpolation -
              value:
                TemplateStr
                  values:
                    Interpolation a
                      value:
                        Name x
                      str:
                        Constant 'x'
                      format_spec: -
              str:
                Constant 't"{x!a}"'
              format_spec: -
    Expr @9:0-9:11
      value:
        JoinedStr @9:0-9:11
          values:
            FormattedValue -
              value:
                TemplateStr
                  values:
                    Interpolation -
                      value:
                        Name x
                      str:
                        Constant 'x'
                      format_spec: -
              format_spec: -
