code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 1  flags -
  names: __doc__, fetch, walk, ticks
  consts:
      0  None
      1  <code fetch at line 1>
      2  <code walk at line 5>
      3  <code ticks at line 15>
    1       0  LoadConst             0 (None)
            1  StoreName             0 (__doc__)
            2  LoadConst             1 (<code fetch at line 1>)
            3  MakeFunction          0
            4  StoreName             1 (fetch)
    5       5  LoadConst             2 (<code walk at line 5>)
            6  MakeFunction          0
            7  StoreName             2 (walk)
   15       8  LoadConst             3 (<code ticks at line 15>)
            9  MakeFunction          0
           10  StoreName             3 (ticks)
           11  LoadConst             0 (None)
           12  Return

code fetch  file /tmp/c.py  line 1
  args 1 (posonly 0, kwonly 0)  stack 2  flags optimized newlocals coroutine
  varnames: src
  consts:
      0  None
      1  2
    1       0  Nop
    2       1  LoadFast              0 (src)
            2  GetAwaitable          0
            3  LoadConst             0 (None)
            4  YieldFrom
            5  LoadConst             1 (2)
            6  BinaryOp              6 (**)
            7  Return
            8  LoadConst             0 (None)
            9  Return

code walk  file /tmp/c.py  line 5
  args 2 (posonly 0, kwonly 0)  stack 5  blocks 2  flags optimized newlocals coroutine
  varnames: it, cm, c, x
  consts:
      0  None
      1  <code <listcomp> at line 12>
    5       0  Nop
    6       1  LoadFast              1 (cm)
            2  BeforeAsyncWith
            3  GetAwaitable          1
            4  LoadConst             0 (None)
            5  YieldFrom
            6  SetupWith            45
            7  StoreFast             2 (c)
    7       8  LoadFast              0 (it)
            9  GetAIter
      >>   10  SetupFinally         22
           11  GetANext
           12  GetAwaitable          3
           13  LoadConst             0 (None)
           14  YieldFrom
           15  PopBlock
           16  StoreFast             3 (x)
    8      17  LoadFast              3 (x)
           18  PopJumpIfFalse       21
    9      19  PopTop
           20  Jump                 35
    7 >>   21  Jump                 10
      >>   22  EndAsyncFor
   11      23  LoadFast              2 (c)
    6      24  RotTwo
           25  PopBlock
           26  LoadConst             0 (None)
           27  DupTop
           28  DupTop
           29  Call                  3
           30  GetAwaitable          2
           31  LoadConst             0 (None)
           32  YieldFrom
           33  PopTop
   11      34  Return
    6 >>   35  PopBlock
           36  LoadConst             0 (None)
           37  DupTop
           38  DupTop
           39  Call                  3
           40  GetAwaitable          2
           41  LoadConst             0 (None)
           42  YieldFrom
           43  PopTop
           44  Jump                 53
      >>   45  WithExceptStart
           46  GetAwaitable          2
           47  LoadConst             0 (None)
           48  YieldFrom
           49  PopJumpIfTrue        51
           50  Reraise               0
      >>   51  PopTop
           52  PopTop
   12 >>   53  LoadConst             1 (<code <listcomp> at line 12>)
           54  MakeFunction          0
           55  LoadFast              0 (it)
           56  GetAIter
           57  Call                  1
           58  GetAwaitable          0
           59  LoadConst             0 (None)
           60  YieldFrom
           61  Return
           62  LoadConst             0 (None)
           63  Return

code <listcomp>  file /tmp/c.py  line 12
  args 1 (posonly 0, kwonly 0)  stack 4  blocks 1  flags optimized newlocals coroutine
  varnames: .0, y
  consts:
      0  None
   12       0  Nop
            1  BuildList             0
            2  LoadFast              0 (.0)
      >>    3  SetupFinally         18
            4  GetANext
            5  GetAwaitable          3
            6  LoadConst             0 (None)
            7  YieldFrom
            8  PopBlock
            9  StoreFast             1 (y)
           10  LoadFast              1 (y)
           11  GetAwaitable          0
           12  LoadConst             0 (None)
           13  YieldFrom
           14  PopJumpIfFalse        3
           15  LoadFast              1 (y)
           16  ListAppend            2
           17  Jump                  3
      >>   18  EndAsyncFor
           19  Return

code ticks  file /tmp/c.py  line 15
  args 1 (posonly 0, kwonly 0)  stack 2  flags optimized newlocals async_generator
  varnames: n, i
  names: range, fetch
  consts:
      0  None
   15       0  Nop
   16       1  LoadGlobal            0 (range)
            2  LoadFast              0 (n)
            3  Call                  1
            4  GetIter
      >>    5  ForIter              12
            6  StoreFast             1 (i)
   17       7  LoadFast              1 (i)
            8  AsyncGenWrap
            9  YieldValue
           10  PopTop
   16      11  Jump                  5
   18 >>   12  LoadGlobal            1 (fetch)
           13  LoadFast              0 (n)
           14  Call                  1
           15  GetAwaitable          0
           16  LoadConst             0 (None)
           17  YieldFrom
           18  AsyncGenWrap
           19  YieldValue
           20  PopTop
           21  LoadConst             0 (None)
           22  Return
