code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 1  flags -
  names: __doc__, fetch, walk, ticks
  consts:
      0  None
      1  <code fetch at line 1>
      2  <code walk at line 5>
      3  <code ticks at line 15>
    1       0  LoadConst             0 (None)
            1  StoreName             0 (__doc__)
            2  LoadConst             1 (<code fetch at line 1>)
            3  MakeFunction          0
            4  StoreName             1 (fetch)
    5       5  LoadConst             2 (<code walk at line 5>)
            6  MakeFunction          0
            7  StoreName             2 (walk)
   15       8  LoadConst             3 (<code ticks at line 15>)
            9  MakeFunction          0
           10  StoreName             3 (ticks)
           11  LoadConst             0 (None)
           12  Return

code fetch  file /tmp/c.py  line 1
  args 1 (posonly 0, kwonly 0)  stack 2  flags optimized newlocals coroutine
  varnames: src
  consts:
      0  None
      1  2
    2       0  LoadFast              0 (src)
            1  GetAwaitable          0
            2  LoadConst             0 (None)
            3  YieldFrom
            4  LoadConst             1 (2)
            5  BinaryOp              6 (**)
            6  Return
            7  LoadConst             0 (None)
            8  Return

code walk  file /tmp/c.py  line 5
  args 2 (posonly 0, kwonly 0)  stack 5  blocks 2  flags optimized newlocals coroutine
  varnames: it, cm, c, x
  consts:
      0  None
      1  <code <listcomp> at line 12>
    6       0  LoadFast              1 (cm)
            1  BeforeAsyncWith
            2  GetAwaitable          1
            3  LoadConst             0 (None)
            4  YieldFrom
            5  SetupWith            44
            6  StoreFast             2 (c)
    7       7  LoadFast              0 (it)
            8  GetAIter
      >>    9  SetupFinally         21
           10  GetANext
           11  GetAwaitable          3
           12  LoadConst             0 (None)
           13  YieldFrom
           14  PopBlock
           15  StoreFast             3 (x)
    8      16  LoadFast              3 (x)
           17  PopJumpIfFalse       20
    9      18  PopTop
           19  Jump                 34
    7 >>   20  Jump                  9
      >>   21  EndAsyncFor
   11      22  LoadFast              2 (c)
    6      23  RotTwo
           24  PopBlock
           25  LoadConst             0 (None)
           26  DupTop
           27  DupTop
           28  Call                  3
           29  GetAwaitable          2
           30  LoadConst             0 (None)
           31  YieldFrom
           32  PopTop
   11      33  Return
    6 >>   34  PopBlock
           35  LoadConst             0 (None)
           36  DupTop
           37  DupTop
           38  Call                  3
           39  GetAwaitable          2
           40  LoadConst             0 (None)
           41  YieldFrom
           42  PopTop
           43  Jump                 52
      >>   44  WithExceptStart
           45  GetAwaitable          2
           46  LoadConst             0 (None)
           47  YieldFrom
           48  PopJumpIfTrue        50
           49  Reraise               0
      >>   50  PopTop
           51  PopTop
   12 >>   52  LoadConst             1 (<code <listcomp> at line 12>)
           53  MakeFunction          0
           54  LoadFast              0 (it)
           55  GetAIter
           56  Call                  1
           57  GetAwaitable          0
           58  LoadConst             0 (None)
           59  YieldFrom
           60  Return
           61  LoadConst             0 (None)
           62  Return

code <listcomp>  file /tmp/c.py  line 12
  args 1 (posonly 0, kwonly 0)  stack 4  blocks 1  flags optimized newlocals coroutine
  varnames: .0, y
  consts:
      0  None
   12       0  BuildList             0
            1  LoadFast              0 (.0)
      >>    2  SetupFinally         17
            3  GetANext
            4  GetAwaitable          3
            5  LoadConst             0 (None)
            6  YieldFrom
            7  PopBlock
            8  StoreFast             1 (y)
            9  LoadFast              1 (y)
           10  GetAwaitable          0
           11  LoadConst             0 (None)
           12  YieldFrom
           13  PopJumpIfFalse        2
           14  LoadFast              1 (y)
           15  ListAppend            2
           16  Jump                  2
      >>   17  EndAsyncFor
           18  Return

code ticks  file /tmp/c.py  line 15
  args 1 (posonly 0, kwonly 0)  stack 2  flags optimized newlocals async_generator
  varnames: n, i
  names: range, fetch
  consts:
      0  None
   16       0  LoadGlobal            0 (range)
            1  LoadFast              0 (n)
            2  Call                  1
            3  GetIter
      >>    4  ForIter              11
            5  StoreFast             1 (i)
   17       6  LoadFast              1 (i)
            7  AsyncGenWrap
            8  YieldValue
            9  PopTop
   16      10  Jump                  4
   18 >>   11  LoadGlobal            1 (fetch)
           12  LoadFast              0 (n)
           13  Call                  1
           14  GetAwaitable          0
           15  LoadConst             0 (None)
           16  YieldFrom
           17  AsyncGenWrap
           18  YieldValue
           19  PopTop
           20  LoadConst             0 (None)
           21  Return
