code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 5  flags -
  names: __doc__, a, b, c, d, e, f, g, h, print
  consts:
      0  None
      1  1
      2  2
      3  3
      4  'hi'
      5  'x'
      6  '-'
      7  ('sep',)
    1       0  Nop
            1  LoadConst             0 (None)
            2  StoreName             0 (__doc__)
            3  LoadConst             1 (1)
            4  StoreName             1 (a)
    2       5  LoadName              1 (a)
            6  LoadConst             2 (2)
            7  LoadConst             3 (3)
            8  BinaryOp              2 (*)
            9  BinaryOp              0 (+)
           10  StoreName             2 (b)
    3      11  LoadConst             4 ('hi')
           12  StoreName             3 (c)
    4      13  LoadConst             1 (1)
           14  LoadConst             2 (2)
           15  LoadName              1 (a)
           16  BuildTuple            3
           17  StoreName             4 (d)
    5      18  LoadName              1 (a)
           19  LoadName              2 (b)
           20  LoadName              3 (c)
           21  BuildList             3
           22  StoreName             5 (e)
    6      23  LoadConst             1 (1)
           24  LoadConst             5 ('x')
           25  LoadName              1 (a)
           26  LoadName              2 (b)
           27  BuildMap              2
           28  StoreName             6 (f)
    7      29  LoadConst             1 (1)
           30  LoadConst             2 (2)
           31  LoadName              1 (a)
           32  BuildSet              3
           33  StoreName             7 (g)
    8      34  LoadName              1 (a)
           35  UnaryOp               3 (-)
           36  StoreName             8 (h)
    9      37  LoadName              9 (print)
           38  LoadName              2 (b)
           39  LoadName              3 (c)
           40  LoadConst             6 ('-')
           41  LoadConst             7 (('sep',))
           42  CallKw                3
           43  PopTop
   10      44  LoadName              2 (b)
           45  LoadName              1 (a)
           46  BuildTuple            2
           47  UnpackSequence        2
           48  StoreName             1 (a)
           49  StoreName             2 (b)
           50  LoadConst             0 (None)
           51  Return
