code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 5  flags -
  names: a, b, c, d, e, f, g, h, print
  consts:
      0  1
      1  2
      2  3
      3  'hi'
      4  'x'
      5  '-'
      6  ('sep',)
      7  None
    1       0  LoadConst             0 (1)
            1  StoreName             0 (a)
    2       2  LoadName              0 (a)
            3  LoadConst             1 (2)
            4  LoadConst             2 (3)
            5  BinaryOp              2 (*)
            6  BinaryOp              0 (+)
            7  StoreName             1 (b)
    3       8  LoadConst             3 ('hi')
            9  StoreName             2 (c)
    4      10  LoadConst             0 (1)
           11  LoadConst             1 (2)
           12  LoadName              0 (a)
           13  BuildTuple            3
           14  StoreName             3 (d)
    5      15  LoadName              0 (a)
           16  LoadName              1 (b)
           17  LoadName              2 (c)
           18  BuildList             3
           19  StoreName             4 (e)
    6      20  LoadConst             0 (1)
           21  LoadConst             4 ('x')
           22  LoadName              0 (a)
           23  LoadName              1 (b)
           24  BuildMap              2
           25  StoreName             5 (f)
    7      26  LoadConst             0 (1)
           27  LoadConst             1 (2)
           28  LoadName              0 (a)
           29  BuildSet              3
           30  StoreName             6 (g)
    8      31  LoadName              0 (a)
           32  UnaryOp               3 (-)
           33  StoreName             7 (h)
    9      34  LoadName              8 (print)
           35  LoadName              1 (b)
           36  LoadName              2 (c)
           37  LoadConst             5 ('-')
           38  LoadConst             6 (('sep',))
           39  CallKw                3
           40  PopTop
   10      41  LoadName              1 (b)
           42  LoadName              0 (a)
           43  BuildTuple            2
           44  UnpackSequence        2
           45  StoreName             0 (a)
           46  StoreName             1 (b)
           47  LoadConst             7 (None)
           48  Return
