code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 6  flags -
  names: __doc__, Empty, object, Point, type, Meta
  consts:
      0  None
      1  <code Empty at line 1>
      2  'Empty'
      3  <code Point at line 4>
      4  'Point'
      5  <code Meta at line 14>
      6  'Meta'
      7  ('metaclass',)
    1       0  LoadConst             0 (None)
            1  StoreName             0 (__doc__)
            2  LoadBuildClass
            3  LoadConst             1 (<code Empty at line 1>)
            4  MakeFunction          0
            5  LoadConst             2 ('Empty')
            6  Call                  2
            7  StoreName             1 (Empty)
    4       8  LoadBuildClass
            9  LoadConst             3 (<code Point at line 4>)
           10  MakeFunction          0
           11  LoadConst             4 ('Point')
           12  LoadName              2 (object)
           13  Call                  3
           14  StoreName             3 (Point)
   14      15  LoadBuildClass
           16  LoadConst             5 (<code Meta at line 14>)
           17  MakeFunction          0
           18  LoadConst             6 ('Meta')
           19  LoadName              3 (Point)
           20  LoadName              4 (type)
           21  LoadConst             7 (('metaclass',))
           22  CallKw                4
           23  StoreName             5 (Meta)
           24  LoadConst             0 (None)
           25  Return

code Empty  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 1  flags -
  names: __name__, __module__, __qualname__, __firstlineno__, __static_attributes__
  consts:
      0  'Empty'
      1  1
      2  ()
      3  None
    1       0  LoadName              0 (__name__)
            1  StoreName             1 (__module__)
            2  LoadConst             0 ('Empty')
            3  StoreName             2 (__qualname__)
            4  LoadConst             1 (1)
            5  StoreName             3 (__firstlineno__)
            6  LoadConst             2 (())
            7  StoreName             4 (__static_attributes__)
            8  LoadConst             3 (None)
            9  Return

code Point  file /tmp/c.py  line 4
  args 0 (posonly 0, kwonly 0)  stack 1  flags -
  names: __name__, __module__, __qualname__, __firstlineno__, kind, __init__, norm, __static_attributes__
  consts:
      0  'Point'
      1  4
      2  'point'
      3  <code __init__ at line 7>
      4  <code norm at line 11>
      5  ('x', 'y')
      6  None
    4       0  LoadName              0 (__name__)
            1  StoreName             1 (__module__)
            2  LoadConst             0 ('Point')
            3  StoreName             2 (__qualname__)
            4  LoadConst             1 (4)
            5  StoreName             3 (__firstlineno__)
    5       6  LoadConst             2 ('point')
            7  StoreName             4 (kind)
    7       8  LoadConst             3 (<code __init__ at line 7>)
            9  MakeFunction          0
           10  StoreName             5 (__init__)
   11      11  LoadConst             4 (<code norm at line 11>)
           12  MakeFunction          0
           13  StoreName             6 (norm)
           14  LoadConst             5 (('x', 'y'))
           15  StoreName             7 (__static_attributes__)
           16  LoadConst             6 (None)
           17  Return

code __init__  file /tmp/c.py  line 7
  args 3 (posonly 0, kwonly 0)  stack 2  flags optimized newlocals
  varnames: self, x, y
  names: x, y
  consts:
      0  None
    8       0  LoadFast              1 (x)
            1  LoadFast              0 (self)
            2  StoreAttr             0 (x)
    9       3  LoadFast              2 (y)
            4  LoadFast              0 (self)
            5  StoreAttr             1 (y)
            6  LoadConst             0 (None)
            7  Return

code norm  file /tmp/c.py  line 11
  args 1 (posonly 0, kwonly 0)  stack 3  flags optimized newlocals
  varnames: self
  names: x, y
  consts:
      0  None
   12       0  LoadFast              0 (self)
            1  LoadAttr              0 (x)
            2  LoadFast              0 (self)
            3  LoadAttr              0 (x)
            4  BinaryOp              2 (*)
            5  LoadFast              0 (self)
            6  LoadAttr              1 (y)
            7  LoadFast              0 (self)
            8  LoadAttr              1 (y)
            9  BinaryOp              2 (*)
           10  BinaryOp              0 (+)
           11  Return
           12  LoadConst             0 (None)
           13  Return

code Meta  file /tmp/c.py  line 14
  args 0 (posonly 0, kwonly 0)  stack 1  flags -
  names: __name__, __module__, __qualname__, __firstlineno__, __static_attributes__
  consts:
      0  'Meta'
      1  14
      2  ()
      3  None
   14       0  LoadName              0 (__name__)
            1  StoreName             1 (__module__)
            2  LoadConst             0 ('Meta')
            3  StoreName             2 (__qualname__)
            4  LoadConst             1 (14)
            5  StoreName             3 (__firstlineno__)
            6  LoadConst             2 (())
            7  StoreName             4 (__static_attributes__)
            8  LoadConst             3 (None)
            9  Return
