code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 6  flags -
  names: __doc__, Empty, object, Point, type, Meta
  consts:
      0  None
      1  <code Empty at line 1>
      2  'Empty'
      3  <code Point at line 4>
      4  'Point'
      5  <code Meta at line 14>
      6  'Meta'
      7  ('metaclass',)
    1       0  Nop
            1  LoadConst             0 (None)
            2  StoreName             0 (__doc__)
            3  LoadBuildClass
            4  LoadConst             1 (<code Empty at line 1>)
            5  MakeFunction          0
            6  LoadConst             2 ('Empty')
            7  Call                  2
            8  StoreName             1 (Empty)
    4       9  LoadBuildClass
           10  LoadConst             3 (<code Point at line 4>)
           11  MakeFunction          0
           12  LoadConst             4 ('Point')
           13  LoadName              2 (object)
           14  Call                  3
           15  StoreName             3 (Point)
   14      16  LoadBuildClass
           17  LoadConst             5 (<code Meta at line 14>)
           18  MakeFunction          0
           19  LoadConst             6 ('Meta')
           20  LoadName              3 (Point)
           21  LoadName              4 (type)
           22  LoadConst             7 (('metaclass',))
           23  CallKw                4
           24  StoreName             5 (Meta)
           25  LoadConst             0 (None)
           26  Return

code Empty  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 1  flags -
  names: __name__, __module__, __qualname__, __firstlineno__, __static_attributes__
  consts:
      0  'Empty'
      1  1
      2  ()
      3  None
    1       0  Nop
            1  LoadName              0 (__name__)
            2  StoreName             1 (__module__)
            3  LoadConst             0 ('Empty')
            4  StoreName             2 (__qualname__)
            5  LoadConst             1 (1)
            6  StoreName             3 (__firstlineno__)
    2       7  Nop
            8  LoadConst             2 (())
            9  StoreName             4 (__static_attributes__)
           10  LoadConst             3 (None)
           11  Return

code Point  file /tmp/c.py  line 4
  args 0 (posonly 0, kwonly 0)  stack 1  flags -
  names: __name__, __module__, __qualname__, __firstlineno__, kind, __init__, norm, __static_attributes__
  consts:
      0  'Point'
      1  4
      2  'point'
      3  <code __init__ at line 7>
      4  <code norm at line 11>
      5  ('x', 'y')
      6  None
    4       0  Nop
            1  LoadName              0 (__name__)
            2  StoreName             1 (__module__)
            3  LoadConst             0 ('Point')
            4  StoreName             2 (__qualname__)
            5  LoadConst             1 (4)
            6  StoreName             3 (__firstlineno__)
    5       7  LoadConst             2 ('point')
            8  StoreName             4 (kind)
    7       9  LoadConst             3 (<code __init__ at line 7>)
           10  MakeFunction          0
           11  StoreName             5 (__init__)
   11      12  LoadConst             4 (<code norm at line 11>)
           13  MakeFunction          0
           14  StoreName             6 (norm)
           15  LoadConst             5 (('x', 'y'))
           16  StoreName             7 (__static_attributes__)
           17  LoadConst             6 (None)
           18  Return

code __init__  file /tmp/c.py  line 7
  args 3 (posonly 0, kwonly 0)  stack 2  flags optimized newlocals
  varnames: self, x, y
  names: x, y
  consts:
      0  None
    7       0  Nop
    8       1  LoadFast              1 (x)
            2  LoadFast              0 (self)
            3  StoreAttr             0 (x)
    9       4  LoadFast              2 (y)
            5  LoadFast              0 (self)
            6  StoreAttr             1 (y)
            7  LoadConst             0 (None)
            8  Return

code norm  file /tmp/c.py  line 11
  args 1 (posonly 0, kwonly 0)  stack 3  flags optimized newlocals
  varnames: self
  names: x, y
  consts:
      0  None
   11       0  Nop
   12       1  LoadFast              0 (self)
            2  LoadAttr              0 (x)
            3  LoadFast              0 (self)
            4  LoadAttr              0 (x)
            5  BinaryOp              2 (*)
            6  LoadFast              0 (self)
            7  LoadAttr              1 (y)
            8  LoadFast              0 (self)
            9  LoadAttr              1 (y)
           10  BinaryOp              2 (*)
           11  BinaryOp              0 (+)
           12  Return
           13  LoadConst             0 (None)
           14  Return

code Meta  file /tmp/c.py  line 14
  args 0 (posonly 0, kwonly 0)  stack 1  flags -
  names: __name__, __module__, __qualname__, __firstlineno__, __static_attributes__
  consts:
      0  'Meta'
      1  14
      2  ()
      3  None
   14       0  Nop
            1  LoadName              0 (__name__)
            2  StoreName             1 (__module__)
            3  LoadConst             0 ('Meta')
            4  StoreName             2 (__qualname__)
            5  LoadConst             1 (14)
            6  StoreName             3 (__firstlineno__)
   15       7  Nop
            8  LoadConst             2 (())
            9  StoreName             4 (__static_attributes__)
           10  LoadConst             3 (None)
           11  Return
