code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 3  flags -
  names: __doc__, range, xs, ys, zs, gs, nested
  consts:
      0  None
      1  <code <listcomp> at line 1>
      2  5
      3  <code <setcomp> at line 2>
      4  <code <dictcomp> at line 3>
      5  <code <genexpr> at line 4>
      6  <code <listcomp> at line 5>
    1       0  Nop
            1  LoadConst             0 (None)
            2  StoreName             0 (__doc__)
            3  LoadConst             1 (<code <listcomp> at line 1>)
            4  MakeFunction          0
            5  LoadName              1 (range)
            6  LoadConst             2 (5)
            7  Call                  1
            8  GetIter
            9  Call                  1
           10  StoreName             2 (xs)
    2      11  LoadConst             3 (<code <setcomp> at line 2>)
           12  MakeFunction          0
           13  LoadName              2 (xs)
           14  GetIter
           15  Call                  1
           16  StoreName             3 (ys)
    3      17  LoadConst             4 (<code <dictcomp> at line 3>)
           18  MakeFunction          0
           19  LoadName              2 (xs)
           20  GetIter
           21  Call                  1
           22  StoreName             4 (zs)
    4      23  LoadConst             5 (<code <genexpr> at line 4>)
           24  MakeFunction          0
           25  LoadName              2 (xs)
           26  GetIter
           27  Call                  1
           28  StoreName             5 (gs)
    5      29  LoadConst             6 (<code <listcomp> at line 5>)
           30  MakeFunction          0
           31  LoadName              2 (xs)
           32  GetIter
           33  Call                  1
           34  StoreName             6 (nested)
           35  LoadConst             0 (None)
           36  Return

code <listcomp>  file /tmp/c.py  line 1
  args 1 (posonly 0, kwonly 0)  stack 4  flags optimized newlocals
  varnames: .0, i
  consts:
      0  2
    1       0  Nop
            1  BuildList             0
            2  LoadFast              0 (.0)
      >>    3  ForIter              12
            4  StoreFast             1 (i)
            5  LoadFast              1 (i)
            6  PopJumpIfFalse        3
            7  LoadFast              1 (i)
            8  LoadConst             0 (2)
            9  BinaryOp              2 (*)
           10  ListAppend            2
           11  Jump                  3
      >>   12  Return

code <setcomp>  file /tmp/c.py  line 2
  args 1 (posonly 0, kwonly 0)  stack 3  flags optimized newlocals
  varnames: .0, i
    2       0  Nop
            1  BuildSet              0
            2  LoadFast              0 (.0)
      >>    3  ForIter               8
            4  StoreFast             1 (i)
            5  LoadFast              1 (i)
            6  SetAdd                2
            7  Jump                  3
      >>    8  Return

code <dictcomp>  file /tmp/c.py  line 3
  args 1 (posonly 0, kwonly 0)  stack 5  flags optimized newlocals
  varnames: .0, i
  consts:
      0  2
      1  9
    3       0  Nop
            1  BuildMap              0
            2  LoadFast              0 (.0)
      >>    3  ForIter              19
            4  StoreFast             1 (i)
            5  LoadFast              1 (i)
            6  LoadConst             0 (2)
            7  CompareOp             4 (>)
            8  PopJumpIfFalse        3
            9  LoadFast              1 (i)
           10  LoadConst             1 (9)
           11  CompareOp             2 (<)
           12  PopJumpIfFalse        3
           13  LoadFast              1 (i)
           14  LoadFast              1 (i)
           15  LoadFast              1 (i)
           16  BinaryOp              2 (*)
           17  MapAdd                2
           18  Jump                  3
      >>   19  Return

code <genexpr>  file /tmp/c.py  line 4
  args 1 (posonly 0, kwonly 0)  stack 2  flags optimized newlocals generator
  varnames: .0, i
  consts:
      0  None
    4       0  Nop
            1  LoadFast              0 (.0)
      >>    2  ForIter               8
            3  StoreFast             1 (i)
            4  LoadFast              1 (i)
            5  YieldValue
            6  PopTop
            7  Jump                  2
      >>    8  LoadConst             0 (None)
            9  Return

code <listcomp>  file /tmp/c.py  line 5
  args 1 (posonly 0, kwonly 0)  stack 5  flags optimized newlocals
  varnames: .0, i, j
  names: ys
    5       0  Nop
            1  BuildList             0
            2  LoadFast              0 (.0)
      >>    3  ForIter              19
            4  StoreFast             1 (i)
            5  LoadGlobal            0 (ys)
            6  GetIter
      >>    7  ForIter              18
            8  StoreFast             2 (j)
            9  LoadFast              1 (i)
           10  LoadFast              2 (j)
           11  CompareOp             1 (!=)
           12  PopJumpIfFalse        7
           13  LoadFast              1 (i)
           14  LoadFast              2 (j)
           15  BuildTuple            2
           16  ListAppend            3
           17  Jump                  7
      >>   18  Jump                  3
      >>   19  Return
