code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 3  flags -
  names: __doc__, range, xs, ys, zs, gs, nested
  consts:
      0  None
      1  <code <listcomp> at line 1>
      2  5
      3  <code <setcomp> at line 2>
      4  <code <dictcomp> at line 3>
      5  <code <genexpr> at line 4>
      6  <code <listcomp> at line 5>
    1       0  LoadConst             0 (None)
            1  StoreName             0 (__doc__)
            2  LoadConst             1 (<code <listcomp> at line 1>)
            3  MakeFunction          0
            4  LoadName              1 (range)
            5  LoadConst             2 (5)
            6  Call                  1
            7  GetIter
            8  Call                  1
            9  StoreName             2 (xs)
    2      10  LoadConst             3 (<code <setcomp> at line 2>)
           11  MakeFunction          0
           12  LoadName              2 (xs)
           13  GetIter
           14  Call                  1
           15  StoreName             3 (ys)
    3      16  LoadConst             4 (<code <dictcomp> at line 3>)
           17  MakeFunction          0
           18  LoadName              2 (xs)
           19  GetIter
           20  Call                  1
           21  StoreName             4 (zs)
    4      22  LoadConst             5 (<code <genexpr> at line 4>)
           23  MakeFunction          0
           24  LoadName              2 (xs)
           25  GetIter
           26  Call                  1
           27  StoreName             5 (gs)
    5      28  LoadConst             6 (<code <listcomp> at line 5>)
           29  MakeFunction          0
           30  LoadName              2 (xs)
           31  GetIter
           32  Call                  1
           33  StoreName             6 (nested)
           34  LoadConst             0 (None)
           35  Return

code <listcomp>  file /tmp/c.py  line 1
  args 1 (posonly 0, kwonly 0)  stack 4  flags newlocals
  varnames: .0, i
  consts:
      0  2
    1       0  BuildList             0
            1  LoadFast              0 (.0)
      >>    2  ForIter              11
            3  StoreFast             1 (i)
            4  LoadFast              1 (i)
            5  PopJumpIfFalse        2
            6  LoadFast              1 (i)
            7  LoadConst             0 (2)
            8  BinaryOp              2 (*)
            9  ListAppend            2
           10  Jump                  2
      >>   11  Return

code <setcomp>  file /tmp/c.py  line 2
  args 1 (posonly 0, kwonly 0)  stack 3  flags newlocals
  varnames: .0, i
    2       0  BuildSet              0
            1  LoadFast              0 (.0)
      >>    2  ForIter               7
            3  StoreFast             1 (i)
            4  LoadFast              1 (i)
            5  SetAdd                2
            6  Jump                  2
      >>    7  Return

code <dictcomp>  file /tmp/c.py  line 3
  args 1 (posonly 0, kwonly 0)  stack 5  flags newlocals
  varnames: .0, i
  consts:
      0  2
      1  9
    3       0  BuildMap              0
            1  LoadFast              0 (.0)
      >>    2  ForIter              18
            3  StoreFast             1 (i)
            4  LoadFast              1 (i)
            5  LoadConst             0 (2)
            6  CompareOp             4 (>)
            7  PopJumpIfFalse        2
            8  LoadFast              1 (i)
            9  LoadConst             1 (9)
           10  CompareOp             2 (<)
           11  PopJumpIfFalse        2
           12  LoadFast              1 (i)
           13  LoadFast              1 (i)
           14  LoadFast              1 (i)
           15  BinaryOp              2 (*)
           16  MapAdd                2
           17  Jump                  2
      >>   18  Return

code <genexpr>  file /tmp/c.py  line 4
  args 1 (posonly 0, kwonly 0)  stack 2  flags generator newlocals
  varnames: .0, i
  consts:
      0  None
    4       0  LoadFast              0 (.0)
      >>    1  ForIter               7
            2  StoreFast             1 (i)
            3  LoadFast              1 (i)
            4  YieldValue
            5  PopTop
            6  Jump                  1
      >>    7  LoadConst             0 (None)
            8  Return

code <listcomp>  file /tmp/c.py  line 5
  args 1 (posonly 0, kwonly 0)  stack 5  flags newlocals
  varnames: .0, i, j
  names: ys
    5       0  BuildList             0
            1  LoadFast              0 (.0)
      >>    2  ForIter              18
            3  StoreFast             1 (i)
            4  LoadGlobal            0 (ys)
            5  GetIter
      >>    6  ForIter              17
            7  StoreFast             2 (j)
            8  LoadFast              1 (i)
            9  LoadFast              2 (j)
           10  CompareOp             1 (!=)
           11  PopJumpIfFalse        6
           12  LoadFast              1 (i)
           13  LoadFast              2 (j)
           14  BuildTuple            2
           15  ListAppend            3
           16  Jump                  6
      >>   17  Jump                  2
      >>   18  Return
