code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 4  flags -
  names: __doc__, n, range, i, j, x
  consts:
      0  None
      1  0
      2  10
      3  1
      4  3
      5  7
      6  4
      7  2
    1       0  LoadConst             0 (None)
            1  StoreName             0 (__doc__)
            2  LoadConst             1 (0)
            3  StoreName             1 (n)
    2 >>    4  LoadName              1 (n)
            5  LoadConst             2 (10)
            6  CompareOp             2 (<)
            7  PopJumpIfFalse       23
    3       8  LoadName              1 (n)
            9  LoadConst             3 (1)
           10  BinaryOp              0 (+)
           11  StoreName             1 (n)
    4      12  LoadName              1 (n)
           13  LoadConst             4 (3)
           14  CompareOp             0 (==)
           15  PopJumpIfFalse       17
    5      16  Jump                  4
    6 >>   17  LoadName              1 (n)
           18  LoadConst             5 (7)
           19  CompareOp             0 (==)
           20  PopJumpIfFalse       22
    7      21  Jump                 26
    2 >>   22  Jump                  4
    9 >>   23  LoadConst             3 (1)
           24  UnaryOp               3 (-)
           25  StoreName             1 (n)
   11 >>   26  LoadName              2 (range)
           27  LoadConst             6 (4)
           28  Call                  1
           29  GetIter
      >>   30  ForIter              50
           31  StoreName             3 (i)
   12      32  LoadName              2 (range)
           33  LoadConst             6 (4)
           34  Call                  1
           35  GetIter
      >>   36  ForIter              45
           37  StoreName             4 (j)
   13      38  LoadName              3 (i)
           39  LoadName              4 (j)
           40  CompareOp             0 (==)
           41  PopJumpIfFalse       44
   14      42  PopTop
           43  Jump                 49
   12 >>   44  Jump                 36
   16 >>   45  LoadName              1 (n)
           46  LoadName              3 (i)
           47  BinaryOp              0 (+)
           48  StoreName             1 (n)
   11 >>   49  Jump                 30
   18 >>   50  LoadName              1 (n)
           51  LoadConst             1 (0)
           52  CompareOp             4 (>)
           53  PopJumpIfFalse       57
   19      54  LoadConst             3 (1)
           55  StoreName             5 (x)
   18      56  Jump                 66
   20 >>   57  LoadName              1 (n)
           58  LoadConst             1 (0)
           59  CompareOp             2 (<)
           60  PopJumpIfFalse       64
   21      61  LoadConst             7 (2)
           62  StoreName             5 (x)
   20      63  Jump                 66
   23 >>   64  LoadConst             4 (3)
           65  StoreName             5 (x)
      >>   66  LoadConst             0 (None)
           67  Return
