code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 11  flags -
  names: __doc__, x, w, a, b, c, d, e, g, h
  consts:
      0  None
      1  1
      2  8
      3  'plain'
      4  'a'
      5  'b'
      6  'c'
      7  '>'
      8  'x='
      9  'lit'
     10  'tail'
     11  ''
    1       0  Nop
            1  LoadConst             0 (None)
            2  StoreName             0 (__doc__)
            3  LoadConst             1 (1)
            4  StoreName             1 (x)
    2       5  LoadConst             2 (8)
            6  StoreName             2 (w)
    4       7  LoadConst             3 ('plain')
            8  StoreName             3 (a)
    5       9  LoadName              1 (x)
           10  FormatValue           0
           11  StoreName             4 (b)
    6      12  LoadConst             4 ('a')
           13  LoadName              1 (x)
           14  FormatValue           0
           15  LoadConst             5 ('b')
           16  LoadName              1 (x)
           17  FormatValue           0
           18  LoadConst             6 ('c')
           19  BuildString           5
           20  StoreName             5 (c)
    7      21  LoadName              1 (x)
           22  LoadConst             7 ('>')
           23  LoadName              2 (w)
           24  FormatValue           0
           25  BuildString           2
           26  FormatValue         370 (r spec)
           27  StoreName             6 (d)
    8      28  LoadConst             8 ('x=')
           29  LoadName              1 (x)
           30  FormatValue         114 (r)
           31  BuildString           2
           32  StoreName             7 (e)
    9      33  LoadConst             9 ('lit')
           34  LoadName              1 (x)
           35  FormatValue           0
           36  LoadConst            10 ('tail')
           37  BuildString           3
           38  StoreName             8 (g)
   10      39  LoadName              1 (x)
           40  LoadConst            11 ('')
           41  FormatValue         256 (spec)
           42  StoreName             9 (h)
           43  LoadConst             0 (None)
           44  Return
