code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 1  flags -
  names: __doc__, Pair, first, Box
  consts:
      0  None
      1  <code <generic parameters of Pair> at line 1>
      2  <code <generic parameters of first> at line 4>
      3  <code <generic parameters of Box> at line 8>
    1       0  LoadConst             0 (None)
            1  StoreName             0 (__doc__)
            2  LoadConst             1 (<code <generic parameters of Pair> at line 1>)
            3  MakeFunction          0
            4  Call                  0
            5  StoreName             1 (Pair)
    4       6  LoadConst             2 (<code <generic parameters of first> at line 4>)
            7  MakeFunction          0
            8  Call                  0
            9  StoreName             2 (first)
    8      10  LoadConst             3 (<code <generic parameters of Box> at line 8>)
           11  MakeFunction          0
           12  Call                  0
           13  StoreName             3 (Box)
           14  LoadConst             0 (None)
           15  Return

code <generic parameters of Pair>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 4  flags optimized newlocals
  cellvars: T
  consts:
      0  'Pair'
      1  'T'
      2  <code Pair at line 1>
    1       0  LoadConst             0 ('Pair')
            1  LoadConst             1 ('T')
            2  Intrinsic             0 (TYPEVAR)
            3  Copy                  1
            4  StoreDeref            0 (T)
            5  BuildTuple            1
            6  LoadClosure           0 (T)
            7  BuildTuple            1
            8  LoadConst             2 (<code Pair at line 1>)
            9  MakeFunction          4 (closure)
           10  BuildTuple            3
           11  Intrinsic             8 (TYPEALIAS)
           12  Return

code Pair  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 3  flags optimized newlocals nested
  freevars: T
  names: tuple
    1       0  LoadGlobal            0 (tuple)
            1  LoadDeref             0 (T)
            2  LoadDeref             0 (T)
            3  BuildTuple            2
            4  LoadSubscr
            5  Return

code <generic parameters of first>  file /tmp/c.py  line 4
  args 0 (posonly 0, kwonly 0)  stack 4  flags optimized newlocals
  varnames: T, Ts, P
  consts:
      0  'T'
      1  <code T at line 4>
      2  'Ts'
      3  'P'
      4  <code first at line 4>
    4       0  LoadConst             0 ('T')
            1  LoadConst             1 (<code T at line 4>)
            2  MakeFunction          0
            3  Intrinsic             1 (TYPEVAR_WITH_BOUND)
            4  Copy                  1
            5  StoreFast             0 (T)
            6  LoadConst             2 ('Ts')
            7  Intrinsic             4 (TYPEVARTUPLE)
            8  Copy                  1
            9  StoreFast             1 (Ts)
           10  LoadConst             3 ('P')
           11  Intrinsic             3 (PARAMSPEC)
           12  Copy                  1
           13  StoreFast             2 (P)
           14  BuildTuple            3
           15  LoadConst             4 (<code first at line 4>)
           16  MakeFunction          0
           17  RotTwo
           18  Intrinsic             7 (SET_FUNCTION_TYPE_PARAMS)
           19  Return

code T  file /tmp/c.py  line 4
  args 0 (posonly 0, kwonly 0)  stack 1  flags optimized newlocals
  names: int
    4       0  LoadGlobal            0 (int)
            1  Return

code first  file /tmp/c.py  line 4
  args 1 (posonly 0, kwonly 0)  stack 1  flags optimized newlocals
  varnames: x
  consts:
      0  None
    5       0  LoadFast              0 (x)
            1  Return
            2  LoadConst             0 (None)
            3  Return

code <generic parameters of Box>  file /tmp/c.py  line 8
  args 0 (posonly 0, kwonly 0)  stack 5  flags optimized newlocals
  varnames: .generic_base, T
  cellvars: .type_params
  names: Base
  consts:
      0  'T'
      1  <code T at line 8>
      2  <code Box at line 8>
      3  'Box'
    8       0  LoadConst             0 ('T')
            1  Intrinsic             0 (TYPEVAR)
            2  LoadConst             1 (<code T at line 8>)
            3  MakeFunction          0
            4  Intrinsic             5 (SET_TYPEPARAM_DEFAULT)
            5  Copy                  1
            6  StoreFast             1 (T)
            7  BuildTuple            1
            8  StoreDeref            0 (.type_params)
            9  LoadBuildClass
           10  LoadClosure           0 (.type_params)
           11  BuildTuple            1
           12  LoadConst             2 (<code Box at line 8>)
           13  MakeFunction          4 (closure)
           14  LoadConst             3 ('Box')
           15  LoadDeref             0 (.type_params)
           16  Intrinsic             6 (SUBSCRIPT_GENERIC)
           17  StoreFast             0 (.generic_base)
           18  LoadGlobal            0 (Base)
           19  LoadFast              0 (.generic_base)
           20  Call                  4
           21  Return

code T  file /tmp/c.py  line 8
  args 0 (posonly 0, kwonly 0)  stack 1  flags optimized newlocals
  names: str
    8       0  LoadGlobal            0 (str)
            1  Return

code Box  file /tmp/c.py  line 8
  args 0 (posonly 0, kwonly 0)  stack 1  flags nested
  freevars: .type_params
  names: __name__, __module__, __qualname__, __firstlineno__, __type_params__, get, __static_attributes__
  consts:
      0  'Box'
      1  8
      2  <code get at line 9>
      3  ()
      4  None
    8       0  LoadName              0 (__name__)
            1  StoreName             1 (__module__)
            2  LoadConst             0 ('Box')
            3  StoreName             2 (__qualname__)
            4  LoadConst             1 (8)
            5  StoreName             3 (__firstlineno__)
            6  LoadDeref             0 (.type_params)
            7  StoreName             4 (__type_params__)
    9       8  LoadConst             2 (<code get at line 9>)
            9  MakeFunction          0
           10  StoreName             5 (get)
           11  LoadConst             3 (())
           12  StoreName             6 (__static_attributes__)
           13  LoadConst             4 (None)
           14  Return

code get  file /tmp/c.py  line 9
  args 1 (posonly 0, kwonly 0)  stack 1  flags optimized newlocals
  varnames: self
  names: item
  consts:
      0  None
   10       0  LoadFast              0 (self)
            1  LoadAttr              0 (item)
            2  Return
            3  LoadConst             0 (None)
            4  Return
