code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 2  flags -
  names: __doc__, sys, os.path, os, path, p, math, sin, cos, c, , thing, pkg, other
  consts:
      0  None
      1  0
      2  ('sin', 'cos')
      3  1
      4  ('thing',)
      5  2
      6  ('other',)
    1       0  LoadConst             0 (None)
            1  StoreName             0 (__doc__)
            2  LoadConst             1 (0)
            3  LoadConst             0 (None)
            4  ImportName            1 (sys)
            5  StoreName             1 (sys)
    2       6  LoadConst             1 (0)
            7  LoadConst             0 (None)
            8  ImportName            2 (os.path)
            9  StoreName             3 (os)
    3      10  LoadConst             1 (0)
           11  LoadConst             0 (None)
           12  ImportName            2 (os.path)
           13  LoadAttr              4 (path)
           14  StoreName             5 (p)
    4      15  LoadConst             1 (0)
           16  LoadConst             2 (('sin', 'cos'))
           17  ImportName            6 (math)
           18  ImportFrom            7 (sin)
           19  StoreName             7 (sin)
           20  ImportFrom            8 (cos)
           21  StoreName             9 (c)
           22  PopTop
    5      23  LoadConst             3 (1)
           24  LoadConst             4 (('thing',))
           25  ImportName           10 ()
           26  ImportFrom           11 (thing)
           27  StoreName            11 (thing)
           28  PopTop
    6      29  LoadConst             5 (2)
           30  LoadConst             6 (('other',))
           31  ImportName           12 (pkg)
           32  ImportFrom           13 (other)
           33  StoreName            13 (other)
           34  PopTop
           35  LoadConst             0 (None)
           36  Return
