code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 2  flags -
  names: __doc__, sys, os.path, os, path, p, math, sin, cos, c, , thing, pkg, other
  consts:
      0  None
      1  0
      2  ('sin', 'cos')
      3  1
      4  ('thing',)
      5  2
      6  ('other',)
    1       0  Nop
            1  LoadConst             0 (None)
            2  StoreName             0 (__doc__)
            3  LoadConst             1 (0)
            4  LoadConst             0 (None)
            5  ImportName            1 (sys)
            6  StoreName             1 (sys)
    2       7  LoadConst             1 (0)
            8  LoadConst             0 (None)
            9  ImportName            2 (os.path)
           10  StoreName             3 (os)
    3      11  LoadConst             1 (0)
           12  LoadConst             0 (None)
           13  ImportName            2 (os.path)
           14  LoadAttr              4 (path)
           15  StoreName             5 (p)
    4      16  LoadConst             1 (0)
           17  LoadConst             2 (('sin', 'cos'))
           18  ImportName            6 (math)
           19  ImportFrom            7 (sin)
           20  StoreName             7 (sin)
           21  ImportFrom            8 (cos)
           22  StoreName             9 (c)
           23  PopTop
    5      24  LoadConst             3 (1)
           25  LoadConst             4 (('thing',))
           26  ImportName           10 ()
           27  ImportFrom           11 (thing)
           28  StoreName            11 (thing)
           29  PopTop
    6      30  LoadConst             5 (2)
           31  LoadConst             6 (('other',))
           32  ImportName           12 (pkg)
           33  ImportFrom           13 (other)
           34  StoreName            13 (other)
           35  PopTop
           36  LoadConst             0 (None)
           37  Return
