code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 6  blocks 1  flags -
  names: __doc__, json, os, path, p, sep, sys, csv, ImportError, print, a, b
  consts:
      0  None
      1  0
      2  ('path', 'sep')
    1       0  LoadConst             0 (None)
            1  StoreName             0 (__doc__)
            2  LoadConst             1 (0)
            3  LoadConst             0 (None)
            4  LazyImportName        1 (json)
            5  StoreName             1 (json)
    2       6  LoadConst             1 (0)
            7  LoadConst             2 (('path', 'sep'))
            8  LazyImportName        2 (os)
            9  ImportFrom            3 (path)
           10  StoreName             4 (p)
           11  ImportFrom            5 (sep)
           12  StoreName             5 (sep)
           13  PopTop
    3      14  LoadConst             1 (0)
           15  LoadConst             0 (None)
           16  ImportName            6 (sys)
           17  StoreName             6 (sys)
    4      18  SetupFinally         25
    5      19  LoadConst             1 (0)
           20  LoadConst             0 (None)
           21  ImportNameEager       7 (csv)
           22  StoreName             7 (csv)
    4      23  PopBlock
           24  Jump                 37
      >>   25  PushExcInfo
    6      26  DupTop
           27  LoadName              8 (ImportError)
           28  CheckExcMatch
           29  PopJumpIfFalse       36
           30  PopTop
           31  SetupFinally         35
           32  PopBlock
           33  PopExcept
           34  Jump                 37
      >>   35  Reraise               1
    4 >>   36  Reraise               1
    8 >>   37  LoadName              9 (print)
           38  LoadName              1 (json)
           39  LoadName              4 (p)
           40  LoadName              5 (sep)
           41  LoadName             10 (a)
           42  LoadName             11 (b)
           43  BinaryOp             12 (@)
           44  Call                  4
           45  PopTop
    9      46  LoadName             10 (a)
           47  LoadName             11 (b)
           48  InplaceOp            12 (@)
           49  StoreName            10 (a)
           50  LoadConst             0 (None)
           51  Return
