code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 1  flags -
  names: __doc__, f
  consts:
      0  None
      1  <code f at line 1>
    1       0  LoadConst             0 (None)
            1  StoreName             0 (__doc__)
            2  LoadConst             1 (<code f at line 1>)
            3  MakeFunction          0
            4  StoreName             1 (f)
            5  LoadConst             0 (None)
            6  Return

code f  file /tmp/c.py  line 1
  args 1 (posonly 0, kwonly 0)  stack 6  flags optimized newlocals
  varnames: x, a, rest, v, more, py, p
  names: Point, str, bytes
  consts:
      0  0
      1  1
      2  'small'
      3  'k'
      4  None
      5  ('x', 'y')
      6  ()
      7  'text'
    1       0  Nop
    2       1  LoadFast              0 (x)
    3       2  Copy                  1
            3  Copy                  1
            4  LoadConst             0 (0)
            5  CompareOp             0 (==)
            6  PopJumpIfFalse        8
            7  Jump                 15
      >>    8  Copy                  1
            9  LoadConst             1 (1)
           10  CompareOp             0 (==)
           11  PopJumpIfFalse       13
           12  Jump                 15
      >>   13  PopTop
           14  Jump                 20
      >>   15  PopTop
           16  PopTop
    4      17  LoadConst             2 ('small')
           18  Return
    3      19  Jump                139
    5 >>   20  Copy                  1
           21  MatchSequence
           22  PopJumpIfFalse       38
           23  GetLen
           24  LoadConst             1 (1)
           25  CompareOp             5 (>=)
           26  PopJumpIfFalse       38
           27  UnpackEx              1
           28  Swap                  2
           29  Swap                  2
           30  StoreFast             1 (a)
           31  StoreFast             2 (rest)
           32  LoadFast              1 (a)
           33  PopJumpIfFalse       39
           34  PopTop
    6      35  LoadFast              2 (rest)
           36  Return
    5      37  Jump                139
      >>   38  PopTop
    7 >>   39  Copy                  1
           40  MatchMapping
           41  PopJumpIfFalse       74
           42  GetLen
           43  LoadConst             1 (1)
           44  CompareOp             5 (>=)
           45  PopJumpIfFalse       74
           46  LoadConst             3 ('k')
           47  BuildTuple            1
           48  MatchKeys
           49  Copy                  1
           50  LoadConst             4 (None)
           51  CompareOp             9 (is not)
           52  PopJumpIfFalse       72
           53  UnpackSequence        1
           54  Swap                  3
           55  Swap                  2
           56  Swap                  2
           57  CopyDict
           58  Swap                  2
           59  UnpackSequence        1
           60  Copy                  2
           61  Swap                  2
           62  DeleteSubscr
           63  Swap                  2
           64  StoreFast             3 (v)
           65  StoreFast             4 (more)
           66  PopTop
    8      67  LoadFast              3 (v)
           68  LoadFast              4 (more)
           69  BuildTuple            2
           70  Return
    7      71  Jump                139
      >>   72  PopTop
           73  PopTop
      >>   74  PopTop
    9      75  Copy                  1
           76  Copy                  1
           77  LoadGlobal            0 (Point)
           78  LoadConst             5 (('x', 'y'))
           79  MatchClass            0
           80  Copy                  1
           81  LoadConst             4 (None)
           82  CompareOp             9 (is not)
           83  PopJumpIfFalse       98
           84  UnpackSequence        2
           85  LoadConst             0 (0)
           86  CompareOp             0 (==)
           87  PopJumpIfFalse       98
           88  Swap                  2
           89  Swap                  2
           90  StoreFast             5 (py)
           91  StoreFast             6 (p)
           92  PopTop
   10      93  LoadFast              6 (p)
           94  LoadFast              5 (py)
           95  BuildTuple            2
           96  Return
    9      97  Jump                139
      >>   98  PopTop
           99  PopTop
   11     100  Copy                  1
          101  Copy                  1
          102  LoadGlobal            1 (str)
          103  LoadConst             6 (())
          104  MatchClass            0
          105  Copy                  1
          106  LoadConst             4 (None)
          107  CompareOp             9 (is not)
          108  PopJumpIfFalse      111
          109  UnpackSequence        0
          110  Jump                125
      >>  111  PopTop
          112  Copy                  1
          113  LoadGlobal            2 (bytes)
          114  LoadConst             6 (())
          115  MatchClass            0
          116  Copy                  1
          117  LoadConst             4 (None)
          118  CompareOp             9 (is not)
          119  PopJumpIfFalse      122
          120  UnpackSequence        0
          121  Jump                125
      >>  122  PopTop
          123  PopTop
          124  Jump                130
      >>  125  PopTop
          126  PopTop
   12     127  LoadConst             7 ('text')
          128  Return
   11     129  Jump                139
   13 >>  130  LoadConst             4 (None)
          131  CompareOp             8 (is)
          132  PopJumpIfFalse      136
   14     133  LoadConst             4 (None)
          134  Return
   13     135  Jump                139
   15 >>  136  Nop
   16     137  LoadFast              0 (x)
          138  Return
      >>  139  LoadConst             4 (None)
          140  Return
