code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 1  flags -
  names: __doc__, f
  consts:
      0  None
      1  <code f at line 1>
    1       0  LoadConst             0 (None)
            1  StoreName             0 (__doc__)
            2  LoadConst             1 (<code f at line 1>)
            3  MakeFunction          0
            4  StoreName             1 (f)
            5  LoadConst             0 (None)
            6  Return

code f  file /tmp/c.py  line 1
  args 1 (posonly 0, kwonly 0)  stack 6  flags optimized newlocals
  varnames: x, a, rest, v, more, py, p
  names: Point, str, bytes
  consts:
      0  0
      1  1
      2  'small'
      3  'k'
      4  None
      5  ('x', 'y')
      6  ()
      7  'text'
    2       0  LoadFast              0 (x)
    3       1  Copy                  1
            2  Copy                  1
            3  LoadConst             0 (0)
            4  CompareOp             0 (==)
            5  PopJumpIfFalse        7
            6  Jump                 14
      >>    7  Copy                  1
            8  LoadConst             1 (1)
            9  CompareOp             0 (==)
           10  PopJumpIfFalse       12
           11  Jump                 14
      >>   12  PopTop
           13  Jump                 19
      >>   14  PopTop
           15  PopTop
    4      16  LoadConst             2 ('small')
           17  Return
    3      18  Jump                138
    5 >>   19  Copy                  1
           20  MatchSequence
           21  PopJumpIfFalse       37
           22  GetLen
           23  LoadConst             1 (1)
           24  CompareOp             5 (>=)
           25  PopJumpIfFalse       37
           26  UnpackEx              1
           27  Swap                  2
           28  Swap                  2
           29  StoreFast             1 (a)
           30  StoreFast             2 (rest)
           31  LoadFast              1 (a)
           32  PopJumpIfFalse       38
           33  PopTop
    6      34  LoadFast              2 (rest)
           35  Return
    5      36  Jump                138
      >>   37  PopTop
    7 >>   38  Copy                  1
           39  MatchMapping
           40  PopJumpIfFalse       73
           41  GetLen
           42  LoadConst             1 (1)
           43  CompareOp             5 (>=)
           44  PopJumpIfFalse       73
           45  LoadConst             3 ('k')
           46  BuildTuple            1
           47  MatchKeys
           48  Copy                  1
           49  LoadConst             4 (None)
           50  CompareOp             9 (is not)
           51  PopJumpIfFalse       71
           52  UnpackSequence        1
           53  Swap                  3
           54  Swap                  2
           55  Swap                  2
           56  CopyDict
           57  Swap                  2
           58  UnpackSequence        1
           59  Copy                  2
           60  Swap                  2
           61  DeleteSubscr
           62  Swap                  2
           63  StoreFast             3 (v)
           64  StoreFast             4 (more)
           65  PopTop
    8      66  LoadFast              3 (v)
           67  LoadFast              4 (more)
           68  BuildTuple            2
           69  Return
    7      70  Jump                138
      >>   71  PopTop
           72  PopTop
      >>   73  PopTop
    9      74  Copy                  1
           75  Copy                  1
           76  LoadGlobal            0 (Point)
           77  LoadConst             5 (('x', 'y'))
           78  MatchClass            0
           79  Copy                  1
           80  LoadConst             4 (None)
           81  CompareOp             9 (is not)
           82  PopJumpIfFalse       97
           83  UnpackSequence        2
           84  LoadConst             0 (0)
           85  CompareOp             0 (==)
           86  PopJumpIfFalse       97
           87  Swap                  2
           88  Swap                  2
           89  StoreFast             5 (py)
           90  StoreFast             6 (p)
           91  PopTop
   10      92  LoadFast              6 (p)
           93  LoadFast              5 (py)
           94  BuildTuple            2
           95  Return
    9      96  Jump                138
      >>   97  PopTop
           98  PopTop
   11      99  Copy                  1
          100  Copy                  1
          101  LoadGlobal            1 (str)
          102  LoadConst             6 (())
          103  MatchClass            0
          104  Copy                  1
          105  LoadConst             4 (None)
          106  CompareOp             9 (is not)
          107  PopJumpIfFalse      110
          108  UnpackSequence        0
          109  Jump                124
      >>  110  PopTop
          111  Copy                  1
          112  LoadGlobal            2 (bytes)
          113  LoadConst             6 (())
          114  MatchClass            0
          115  Copy                  1
          116  LoadConst             4 (None)
          117  CompareOp             9 (is not)
          118  PopJumpIfFalse      121
          119  UnpackSequence        0
          120  Jump                124
      >>  121  PopTop
          122  PopTop
          123  Jump                129
      >>  124  PopTop
          125  PopTop
   12     126  LoadConst             7 ('text')
          127  Return
   11     128  Jump                138
   13 >>  129  LoadConst             4 (None)
          130  CompareOp             8 (is)
          131  PopJumpIfFalse      135
   14     132  LoadConst             4 (None)
          133  Return
   13     134  Jump                138
   15 >>  135  Nop
   16     136  LoadFast              0 (x)
          137  Return
      >>  138  LoadConst             4 (None)
          139  Return
