code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 1  flags -
  names: __doc__, f, r, w, gen
  consts:
      0  None
      1  <code f at line 1>
      2  <code r at line 10>
      3  <code w at line 16>
      4  <code gen at line 20>
    1       0  LoadConst             0 (None)
            1  StoreName             0 (__doc__)
            2  LoadConst             1 (<code f at line 1>)
            3  MakeFunction          0
            4  StoreName             1 (f)
   10       5  LoadConst             2 (<code r at line 10>)
            6  MakeFunction          0
            7  StoreName             2 (r)
   16       8  LoadConst             3 (<code w at line 16>)
            9  MakeFunction          0
           10  StoreName             3 (w)
   20      11  LoadConst             4 (<code gen at line 20>)
           12  MakeFunction          0
           13  StoreName             4 (gen)
           14  LoadConst             0 (None)
           15  Return

code f  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 3  flags optimized newlocals
  varnames: C
  cellvars: x
  consts:
      0  1
      1  <code C at line 4>
      2  'C'
      3  None
    1       0  Nop
    2       1  LoadConst             0 (1)
            2  StoreDeref            0 (x)
    3       3  DeleteDeref           0 (x)
    4       4  LoadBuildClass
            5  LoadClosure           0 (x)
            6  BuildTuple            1
            7  LoadConst             1 (<code C at line 4>)
            8  MakeFunction          4 (closure)
            9  LoadConst             2 ('C')
           10  Call                  2
           11  StoreFast             0 (C)
    8      12  LoadFast              0 (C)
           13  Return
           14  LoadConst             3 (None)
           15  Return

code C  file /tmp/c.py  line 4
  args 0 (posonly 0, kwonly 0)  stack 1  flags nested
  freevars: x
  names: __name__, __module__, __qualname__, __firstlineno__, y, g, __static_attributes__
  consts:
      0  'f.<locals>.C'
      1  4
      2  1
      3  ()
      4  None
    4       0  Nop
            1  LoadName              0 (__name__)
            2  StoreName             1 (__module__)
            3  LoadConst             0 ('f.<locals>.C')
            4  StoreName             2 (__qualname__)
            5  LoadConst             1 (4)
            6  StoreName             3 (__firstlineno__)
    5       7  LoadDeref             0 (x)
            8  StoreName             4 (y)
    7       9  LoadConst             2 (1)
           10  StoreGlobal           5 (g)
           11  LoadConst             3 (())
           12  StoreName             6 (__static_attributes__)
           13  LoadConst             4 (None)
           14  Return

code r  file /tmp/c.py  line 10
  args 0 (posonly 0, kwonly 0)  stack 1  blocks 1  flags optimized newlocals
  consts:
      0  1
      1  None
   10       0  Nop
   11       1  SetupFinally          9
   12       2  LoadConst             0 (1)
   11       3  PopBlock
   14       4  Nop
   12       5  Return
   11       6  PopBlock
   14       7  Nop
   11       8  Jump                 11
   14 >>    9  Nop
   11      10  Reraise               0
      >>   11  LoadConst             1 (None)
           12  Return

code w  file /tmp/c.py  line 16
  args 0 (posonly 0, kwonly 0)  stack 5  blocks 1  flags optimized newlocals
  names: open
  consts:
      0  'a'
      1  2
      2  None
   16       0  Nop
   17       1  LoadGlobal            0 (open)
            2  LoadConst             0 ('a')
            3  Call                  1
            4  BeforeWith
            5  SetupWith            23
            6  PopTop
   18       7  LoadConst             1 (2)
   17       8  RotTwo
            9  PopBlock
           10  LoadConst             2 (None)
           11  DupTop
           12  DupTop
           13  Call                  3
           14  PopTop
   18      15  Return
   17      16  PopBlock
           17  LoadConst             2 (None)
           18  DupTop
           19  DupTop
           20  Call                  3
           21  PopTop
           22  Jump                 28
      >>   23  WithExceptStart
           24  PopJumpIfTrue        26
           25  Reraise               0
      >>   26  PopTop
           27  PopTop
      >>   28  LoadConst             2 (None)
           29  Return

code gen  file /tmp/c.py  line 20
  args 0 (posonly 0, kwonly 0)  stack 1  flags optimized newlocals generator
  varnames: x
  consts:
      0  1
      1  None
      2  3
   20       0  Nop
   21       1  LoadConst             0 (1)
            2  YieldValue
            3  PopTop
   22       4  LoadConst             1 (None)
            5  YieldValue
            6  StoreFast             0 (x)
   23       7  LoadConst             2 (3)
            8  Return
            9  LoadConst             1 (None)
           10  Return
