code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 1  flags -
  names: __doc__, f, r, w, gen
  consts:
      0  None
      1  <code f at line 1>
      2  <code r at line 10>
      3  <code w at line 16>
      4  <code gen at line 20>
    1       0  LoadConst             0 (None)
            1  StoreName             0 (__doc__)
            2  LoadConst             1 (<code f at line 1>)
            3  MakeFunction          0
            4  StoreName             1 (f)
   10       5  LoadConst             2 (<code r at line 10>)
            6  MakeFunction          0
            7  StoreName             2 (r)
   16       8  LoadConst             3 (<code w at line 16>)
            9  MakeFunction          0
           10  StoreName             3 (w)
   20      11  LoadConst             4 (<code gen at line 20>)
           12  MakeFunction          0
           13  StoreName             4 (gen)
           14  LoadConst             0 (None)
           15  Return

code f  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 3  flags newlocals
  varnames: C
  cellvars: x
  consts:
      0  1
      1  <code C at line 4>
      2  'C'
      3  None
    2       0  LoadConst             0 (1)
            1  StoreDeref            0 (x)
    3       2  DeleteDeref           0 (x)
    4       3  LoadBuildClass
            4  LoadClosure           0 (x)
            5  BuildTuple            1
            6  LoadConst             1 (<code C at line 4>)
            7  MakeFunction          4 (closure)
            8  LoadConst             2 ('C')
            9  Call                  2
           10  StoreFast             0 (C)
    8      11  LoadFast              0 (C)
           12  Return
           13  LoadConst             3 (None)
           14  Return

code C  file /tmp/c.py  line 4
  args 0 (posonly 0, kwonly 0)  stack 1  flags nested
  freevars: x
  names: __doc__, y, g
  consts:
      0  None
      1  1
    4       0  LoadConst             0 (None)
            1  StoreName             0 (__doc__)
    5       2  LoadDeref             0 (x)
            3  StoreName             1 (y)
    7       4  LoadConst             1 (1)
            5  StoreGlobal           2 (g)
            6  LoadConst             0 (None)
            7  Return

code r  file /tmp/c.py  line 10
  args 0 (posonly 0, kwonly 0)  stack 1  blocks 1  flags newlocals
  consts:
      0  1
      1  None
   11       0  SetupFinally          6
   12       1  LoadConst             0 (1)
   11       2  PopBlock
   12       3  Return
   11       4  PopBlock
            5  Jump                  7
      >>    6  Reraise               0
      >>    7  LoadConst             1 (None)
            8  Return

code w  file /tmp/c.py  line 16
  args 0 (posonly 0, kwonly 0)  stack 5  blocks 1  flags newlocals
  names: open
  consts:
      0  'a'
      1  2
      2  None
   17       0  LoadGlobal            0 (open)
            1  LoadConst             0 ('a')
            2  Call                  1
            3  BeforeWith
            4  SetupWith            22
            5  PopTop
   18       6  LoadConst             1 (2)
   17       7  RotTwo
            8  PopBlock
            9  LoadConst             2 (None)
           10  DupTop
           11  DupTop
           12  Call                  3
           13  PopTop
   18      14  Return
   17      15  PopBlock
           16  LoadConst             2 (None)
           17  DupTop
           18  DupTop
           19  Call                  3
           20  PopTop
           21  Jump                 27
      >>   22  WithExceptStart
           23  PopJumpIfTrue        25
           24  Reraise               0
      >>   25  PopTop
           26  PopTop
      >>   27  LoadConst             2 (None)
           28  Return

code gen  file /tmp/c.py  line 20
  args 0 (posonly 0, kwonly 0)  stack 1  flags generator newlocals
  varnames: x
  consts:
      0  1
      1  None
      2  3
   21       0  LoadConst             0 (1)
            1  YieldValue
            2  PopTop
   22       3  LoadConst             1 (None)
            4  YieldValue
            5  StoreFast             0 (x)
   23       6  LoadConst             2 (3)
            7  Return
            8  LoadConst             1 (None)
            9  Return
