code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 5  flags -
  names: __doc__, a, object, o, x, first, rest, most, last, y, z, w, q, t, u, v, s, print, b, d
  consts:
      0  None
      1  0
      2  1
      3  2
      4  3
      5  4
      6  'k'
    1       0  Nop
            1  LoadConst             0 (None)
            2  StoreName             0 (__doc__)
            3  LoadConst             1 (0)
            4  LoadConst             2 (1)
            5  LoadConst             3 (2)
            6  BuildList             3
            7  StoreName             1 (a)
    2       8  LoadConst             2 (1)
            9  LoadName              1 (a)
           10  LoadConst             1 (0)
           11  StoreSubscr
    3      12  LoadName              1 (a)
           13  LoadName              1 (a)
           14  LoadConst             1 (0)
           15  LoadConst             3 (2)
           16  BuildSlice            2
           17  StoreSubscr
    4      18  LoadName              1 (a)
           19  LoadName              1 (a)
           20  LoadConst             0 (None)
           21  LoadConst             0 (None)
           22  LoadConst             3 (2)
           23  BuildSlice            3
           24  StoreSubscr
    5      25  LoadName              1 (a)
           26  LoadConst             1 (0)
           27  DupTop2
           28  LoadSubscr
           29  LoadConst             2 (1)
           30  InplaceOp             0 (+)
           31  RotThree
           32  StoreSubscr
    6      33  LoadName              2 (object)
           34  Call                  0
           35  StoreName             3 (o)
    7      36  LoadConst             2 (1)
           37  LoadName              3 (o)
           38  StoreAttr             4 (x)
    8      39  LoadName              3 (o)
           40  DupTop
           41  LoadAttr              4 (x)
           42  LoadConst             2 (1)
           43  InplaceOp             0 (+)
           44  RotTwo
           45  StoreAttr             4 (x)
    9      46  LoadName              1 (a)
           47  UnpackEx              1
           48  StoreName             5 (first)
           49  StoreName             6 (rest)
   10      50  LoadName              1 (a)
           51  UnpackEx          65536
           52  StoreName             7 (most)
           53  StoreName             8 (last)
   11      54  LoadConst             1 (0)
           55  DupTop
           56  StoreName             4 (x)
           57  DupTop
           58  StoreName             9 (y)
           59  StoreName            10 (z)
   12      60  LoadName              1 (a)
           61  LoadConst             1 (0)
           62  DeleteSubscr
           63  LoadName              3 (o)
           64  DeleteAttr            4 (x)
           65  DeleteName            4 (x)
   13      66  LoadConst             2 (1)
           67  LoadConst             2 (1)
           68  BinaryOp              0 (+)
           69  DupTop
           70  StoreName            11 (w)
           71  StoreName            12 (q)
   14      72  LoadConst             2 (1)
           73  LoadName             11 (w)
           74  DupTop
           75  RotThree
           76  CompareOp             2 (<)
           77  JumpIfFalseOrPop     86
           78  LoadConst             4 (3)
           79  DupTop
           80  RotThree
           81  CompareOp             3 (<=)
           82  JumpIfFalseOrPop     86
           83  LoadConst             5 (4)
           84  CompareOp             1 (!=)
           85  Jump                 88
      >>   86  RotTwo
           87  PopTop
      >>   88  StoreName            13 (t)
   15      89  LoadConst             2 (1)
           90  LoadName             11 (w)
           91  CompareOp             2 (<)
           92  StoreName            14 (u)
   16      93  LoadName             13 (t)
           94  JumpIfFalseOrPop     96
           95  LoadName             14 (u)
      >>   96  JumpIfTrueOrPop      99
           97  LoadName             13 (t)
           98  UnaryOp               1 (not)
      >>   99  StoreName            15 (v)
   17     100  LoadName              1 (a)
          101  LoadConst             2 (1)
          102  LoadConst             3 (2)
          103  LoadConst             2 (1)
          104  BuildSlice            3
          105  LoadSubscr
          106  StoreName            16 (s)
   18     107  LoadName             17 (print)
          108  BuildList             0
          109  LoadName              1 (a)
          110  ListExtend            1
          111  ListToTuple
          112  BuildMap              0
          113  BuildMap              0
          114  DictMerge             1
          115  CallEx                1 (kwargs)
          116  PopTop
   19     117  BuildList             0
          118  LoadName              1 (a)
          119  ListExtend            1
          120  LoadConst             2 (1)
          121  ListAppend            1
          122  LoadName              1 (a)
          123  ListExtend            1
          124  StoreName            18 (b)
   20     125  BuildMap              0
          126  BuildMap              0
          127  DictUpdate            1
          128  LoadConst             6 ('k')
          129  LoadConst             2 (1)
          130  MapAdd                1
          131  StoreName            19 (d)
          132  LoadConst             0 (None)
          133  Return
