code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 7  blocks 2  flags -
  names: __doc__, f, ValueError, e, print, TypeError, KeyError
  consts:
      0  None
    1       0  Nop
            1  LoadConst             0 (None)
            2  StoreName             0 (__doc__)
            3  SetupFinally          9
    2       4  LoadName              1 (f)
            5  Call                  0
            6  PopTop
    1       7  PopBlock
            8  Jump                 67
      >>    9  PushExcInfo
           10  SetupFinally         64
           11  BuildList             0
           12  Copy                  2
    3      13  LoadName              2 (ValueError)
           14  CheckEgMatch
           15  Copy                  1
           16  LoadConst             0 (None)
           17  CompareOp             8 (is)
           18  PopJumpIfTrue        35
           19  StoreName             3 (e)
           20  SetupFinally         30
    4      21  LoadName              4 (print)
           22  LoadName              3 (e)
           23  Call                  1
           24  PopTop
    3      25  PopBlock
           26  LoadConst             0 (None)
           27  StoreName             3 (e)
           28  DeleteName            3 (e)
           29  Jump                 36
      >>   30  LoadConst             0 (None)
           31  StoreName             3 (e)
           32  DeleteName            3 (e)
           33  ListAppend            2
           34  Jump                 36
      >>   35  PopTop
    5 >>   36  LoadName              5 (TypeError)
           37  LoadName              6 (KeyError)
           38  BuildTuple            2
           39  CheckEgMatch
           40  Copy                  1
           41  LoadConst             0 (None)
           42  CompareOp             8 (is)
           43  PopJumpIfTrue        51
           44  PopTop
           45  SetupFinally         49
    6      46  Raise                 0
    5      47  PopBlock
           48  Jump                 52
      >>   49  ListAppend            2
           50  Jump                 52
      >>   51  PopTop
      >>   52  ListAppend            1
    1      53  PrepReraiseStar
           54  Copy                  1
           55  LoadConst             0 (None)
           56  CompareOp             9 (is not)
           57  PopJumpIfTrue        62
           58  PopTop
           59  PopBlock
           60  PopExcept
           61  Jump                 67
      >>   62  PopBlock
           63  Reraise               1
      >>   64  RotTwo
           65  PopTop
           66  Reraise               1
      >>   67  LoadConst             0 (None)
           68  Return
