code <module>  file /tmp/c.py  line 1
  args 0 (posonly 0, kwonly 0)  stack 6  flags -
  names: __doc__, x, y, w, z
  consts:
      0  None
      1  'a'
      2  'b'
      3  ''
      4  'x'
      5  'y'
      6  '>'
    1       0  Nop
            1  LoadConst             0 (None)
            2  StoreName             0 (__doc__)
            3  LoadConst             1 ('a')
            4  LoadConst             2 ('b')
            5  LoadConst             3 ('')
            6  BuildTuple            3
            7  LoadName              1 (x)
            8  LoadConst             4 ('x')
            9  BuildInterpolation    0
           10  LoadName              2 (y)
           11  LoadConst             5 ('y')
           12  LoadConst             6 ('>')
           13  LoadName              3 (w)
           14  FormatValue           0
           15  BuildString           2
           16  BuildInterpolation  370 (r spec)
           17  BuildTuple            2
           18  BuildTemplate
           19  StoreName             1 (x)
    2      20  LoadConst             3 ('')
           21  LoadConst             3 ('')
           22  LoadConst             3 ('')
           23  BuildTuple            3
           24  LoadName              1 (x)
           25  LoadConst             4 ('x')
           26  BuildInterpolation    0
           27  LoadName              2 (y)
           28  LoadConst             5 ('y')
           29  BuildInterpolation    0
           30  BuildTuple            2
           31  BuildTemplate
           32  StoreName             2 (y)
    3      33  LoadConst             3 ('')
           34  BuildTuple            1
           35  BuildTuple            0
           36  BuildTemplate
           37  StoreName             4 (z)
           38  LoadConst             0 (None)
           39  Return
