#!/usr/bin/env python3
"""Turn glorkz into a C++ array the binary carries.

Upstream reads glorkz from the directory the program was first run in, and
compiles it once into adventure.dat. Braam has no seek syscall to index a data
file with, and a package's non-bin payload lands under a path that carries the
version, so the data goes into the binary instead. The parser is still
upstream's; only the source of its bytes changed.
"""

import sys

WIDTH = 16  # bytes a line, so the generated file stays diffable


def main(argv):
    if len(argv) != 3:
        sys.stderr.write("usage: mkdata.py <glorkz> <out.cpp>\n")
        return 2

    with open(argv[1], "rb") as f:
        data = f.read()

    with open(argv[2], "w") as out:
        out.write("// Generated by mkdata.py from %s. Do not edit.\n" %
                  argv[1].rsplit("/", 1)[-1])
        out.write("\n#include \"kernel/types.h\"\n\n")
        out.write("extern const char GLORKZ[%d];\n" % len(data))
        out.write("extern const u32 GLORKZ_LEN;\n\n")
        out.write("const char GLORKZ[%d] = {\n" % len(data))
        for i in range(0, len(data), WIDTH):
            row = data[i:i + WIDTH]
            out.write("    " + " ".join("%3d," % b for b in row) + "\n")
        out.write("};\n\n")
        out.write("const u32 GLORKZ_LEN = %d;\n" % len(data))

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
