// msg.h: what rspeak() and mspeak() say.
//
// glorkz section 6 is the rtext_ table and section 12 is mtext_.  The numbers
// below are the data file's; the names are a summary of the text beside them,
// which is the only way to check one.  linkdata() checks the table has not
// moved under them.
#pragma once

#include "kernel/types.h"

// clang-format off

// rspeak().  None is a real value: rspeak(0) says nothing, and that is what
// actspk_ holds for the two verbs with no default message.
enum class Msg : i16 {
    None = 0,
    ColossalCave = 1,              // Somewhere nearby is colossal cave, where others have found...
    DwarfBlocks = 2,               // A little dwarf with a big knife blocks your way.
    DwarfThrowsAxe = 3,            // A little dwarf just walked around a corner, saw you, threw...
    DwarfInRoom = 4,               // There is a threatening little dwarf in the room with you!
    KnifeThrown = 5,               // One sharp nasty knife is thrown at you!
    NoneHitYou = 6,                // None of them hit you!
    OneGetsYou = 7,                // One of them gets you!
    HollowVoicePlugh = 8,          // A hollow voice says "plugh".
    NoWayThatWay = 9,              // There is no way to go that direction.
    UnsureFacing = 10,             // I am unsure how you are facing.  Use compass points or near...
    UnsureInOut = 11,              // I don't know in from out here.  Use compass points or name...
    WordNotHere = 12,              // I don't know how to apply that word here.
    DontUnderstand = 13,           // I don't understand that!
    ExplainHow = 14,               // I'm game.  Would you care to explain how?
    NoMoreDetail = 15,             // Sorry, but I am not allowed to give more detail.  I will re...
    PitchDark = 16,                // It is now pitch dark.  If you proceed you will likely fall...
    TypeWNotWest = 17,             // If you prefer, simply type w rather than west.
    CatchingBird = 18,             // Are you trying to catch the bird?
    BirdFrightened = 19,           // The bird is frightened right now and you cannot catch it no...
    DealWithSnake = 20,            // Are you trying to somehow deal with the snake?
    CantKillSnake = 21,            // You can't kill the snake, or drive it away, or avoid it, or...
    ReallyQuit = 22,               // Do you really want to quit now?
    FellIntoPit = 23,              // You fell into a pit and broke every bone in your body!
    AlreadyCarrying = 24,          // You are already carrying it!
    CantBeSerious = 25,            // You can't be serious!
    BirdBecomesUneasy = 26,        // The bird was unafraid when you entered, but as you approach...
    CantCarryBird = 27,            // You can catch the bird, but you cannot carry it.
    NothingWithLock = 28,          // There is nothing here with a lock!
    NotCarryingIt = 29,            // You aren't carrying it!
    BirdKillsSnake = 30,           // The little bird attacks the green snake, and in an astoundi...
    NoKeys = 31,                   // You have no keys!
    NoLock = 32,                   // It has no lock.
    CantLockThat = 33,             // I don't know how to lock or unlock such a thing.
    AlreadyLocked = 34,            // It was already locked.
    GrateLocked = 35,              // The grate is now locked.
    GrateUnlocked = 36,            // The grate is now unlocked.
    AlreadyUnlocked = 37,          // It was already unlocked.
    NoLight = 38,                  // You have no source of light.
    LampOn = 39,                   // Your lamp is now on.
    LampOff = 40,                  // Your lamp is now off.
    BearBlocksChain = 41,          // There is no way to get past the bear to unlock the chain, w...
    NothingHappens = 42,           // Nothing happens.
    Where = 43,                    // Where?
    NothingToAttack = 44,          // There is nothing here to attack.
    BirdDead = 45,                 // The little bird is now dead.  Its body disappears.
    SnakeDangerous = 46,           // Attacking the snake both doesn't work and is very dangerous.
    KilledDwarf = 47,              // You killed a little dwarf.
    DwarfDodges = 48,              // You attack a little dwarf, but he dodges out of the way.
    BareHands = 49,                // With what?  Your bare hands?
    WornOutMagicWord = 50,         // Good try, but that is an old worn-out magic word.
    VocabularyHelp = 51,           // I know of places, actions, and things.  Most of my vocabulary
    KnifeMisses = 52,              // It misses!
    KnifeGetsYou = 53,             // It gets you!
    Ok = 54,                       // OK
    CantUnlockKeys = 55,           // You can't unlock the keys.
    CrawledBackToStart = 56,       // You have crawled around in some little holes and wound up b...
    NoStreamOnSurface = 57,        // I don't know where the cave is, but hereabouts no stream ca...
    NeedDetail = 58,               // I need more detailed instructions to do that.
    OnlyTellWhatYouSee = 59,       // I can only tell you what you see as you move about and mani...
    UnknownWord = 60,              // I don't know that word.
    What = 61,                     // What?
    GettingIntoCave = 62,          // Are you trying to get into the cave?
    GrateSolid = 63,               // The grate is very solid and has a hardened steel lock.  You...
    Trees = 64,                    // The trees of the forest are large hardwood oak and maple, w...
    WelcomeInstructions = 65,      // Welcome to adventure!!  Would you like instructions?
    NoShovel = 66,                 // Digging without a shovel is quite impractical.  Even with a...
    NeedDynamite = 67,             // Blasting requires dynamite.
    AsConfusedAsYou = 68,          // I'm as confused as you are.
    Mist = 69,                     // Mist is a white vapor, usually water, seen from time to tim...
    FeetWet = 70,                  // Your feet are now wet.
    LostAppetite = 71,             // I think I just lost my appetite.
    Delicious = 72,                // Thank you, it was delicious!
    DrankFromStream = 73,          // You have taken a drink from the stream.  The water tastes s...
    BottleEmpty = 74,              // The bottle of water is now empty.
    RubbingLamp = 75,              // Rubbing the electric lamp is not particularly rewarding.  A...
    NothingUnexpected = 76,        // Peculiar.  Nothing unexpected happens.
    GroundWet = 77,                // Your bottle is empty and the ground is wet.
    CantPourThat = 78,             // You can't pour that.
    WatchIt = 79,                  // Watch it!
    WhichWay = 80,                 // Which way?
    Killed = 81,                   // Oh dear, you seem to have gotten yourself killed.  I might...
    ReviveOffer = 82,              // All right.  But don't blame me if something goes wr......
    KilledAgain = 83,              // You clumsy oaf, you've done it again!  I don't know how lon...
    ReviveSmoke = 84,              // Okay, now where did I put my orange smoke?....  >poof!<
    KilledThrice = 85,             // Now you've really done it!  I'm out of orange smoke!  You d...
    ReviveRefused = 86,            // Okay, if you're so smart, do it yourself!  I'm leaving!
    ObituarySlots = 90,            // >>> Messages 81 thru 90 are reserved for "obituaries". <<<
    DontRememberHow = 91,          // Sorry, but I no longer seem to remember how it was you got...
    CarryingTooMuch = 92,          // You can't carry anything more.  You'll have to drop somethi...
    GrateBarsTheWay = 93,          // You can't go through a locked steel grate!
    RightHereWithYou = 94,         // I believe what you want is right here with you.
    TwoInchSlit = 95,              // You don't fit through a two-inch slit!
    UseTheBridge = 96,             // I respectfully suggest you go across the bridge instead of...
    NoWayAcrossFissure = 97,       // There is no way across the fissure.
    CarryingNothing = 98,          // You're not carrying anything.
    CurrentlyHolding = 99,         // You are currently holding the following:
    NotHungryFjords = 100,         // It's not hungry (it's merely pinin' for the fjords).  Besid...
    SnakeEatsBird = 101,           // The snake has now devoured your bird.
    NothingItWantsToEat = 102,     // There's nothing here it wants to eat (except perhaps you).
    DwarvesEatCoal = 103,          // You fool, dwarves eat only coal!  Now you've made him *real...
    NothingToCarryItIn = 104,      // You have nothing in which to carry it.
    BottleAlreadyFull = 105,       // Your bottle is already full.
    NothingToFillWith = 106,       // There is nothing here with which to fill the bottle.
    BottleFullWater = 107,         // Your bottle is now full of water.
    BottleFullOil = 108,           // Your bottle is now full of oil.
    CantFillThat = 109,            // You can't fill that.
    DontBeRidiculous = 110,        // Don't be ridiculous!
    DoorRusty = 111,               // The door is extremely rusty and refuses to open.
    PlantWantsWater = 112,         // The plant indignantly shakes the oil off its leaves and ask...
    HingesRusted = 113,            // The hinges are quite thoroughly rusted now and won't budge.
    HingesFreed = 114,             // The oil has freed up the hinges so that the door will now m...
    PlantDeepRoots = 115,          // The plant has exceptionally deep roots and cannot be pulled...
    KnivesVanish = 116,            // The dwarves' knives vanish as they strike the walls of the...
    WontFitThroughTunnel = 117,    // Something you're carrying won't fit through the tunnel with...
    ClamTooBig = 118,              // You can't fit this five-foot clam through that little passage!
    OysterTooBig = 119,            // You can't fit this five-foot oyster through that little pas...
    PutDownClam = 120,             // I advise you to put down the clam before opening it.  >stra...
    PutDownOyster = 121,           // I advise you to put down the oyster before opening it.  >wr...
    NothingOpensClam = 122,        // You don't have anything strong enough to open the clam.
    NothingOpensOyster = 123,      // You don't have anything strong enough to open the oyster.
    PearlFalls = 124,              // A glistening pearl falls out of the clam and rolls away.  G...
    OysterCreaks = 125,            // The oyster creaks open, revealing nothing but oyster inside...
    CrawledFoundWay = 126,         // You have crawled around in some little holes and found your...
    FaintRustling = 127,           // There are faint rustling noises from the darkness behind you.
    PiratePounces = 128,           // Out from the shadows behind you pounces a bearded pirate!...
    CaveClosingSoon = 129,         // A sepulchral voice reverberating through the cave, says, "C...
    RecordedVoice = 130,           // A mysterious recorded voice groans into life and announces:
    LooksLikeYoureDead = 131,      // It looks as though you're dead.  Well, seeing as how it's s...
    CaveNowClosed = 132,           // The sepulchral voice entones, "The cave is now closed."  As...
    BlastDistant = 133,            // there is a loud explosion, and a twenty-foot hole appears i...
    BlastRepository = 134,         // There is a loud explosion, and a twenty-foot hole appears i...
    BlastSplashed = 135,           // There is a loud explosion, and you are suddenly splashed ac...
    DwarvesAwakened = 136,         // The resulting ruckus has awakened the dwarves.  There are n...
    LeaveBirdAlone = 137,          // Oh, leave the poor unhappy bird alone.
    WhateverYouWant = 138,         // I daresay whatever you want is around here somewhere.
    NoWordStop = 139,              // I don't know the word "stop".  Use "quit" if you want to gi...
    CantGetThereFromHere = 140,    // You can't get there from here.
    FollowedByBear = 141,          // You are being followed by a very large, tame bear.
    EndOrSuspend = 142,            // If you want to end your adventure early, say "quit".  To su...
    IndeedQuit = 143,              // Do you indeed wish to quit now?
    NothingToFillVase = 144,       // There is nothing here with which to fill the vase.
    VaseShattered = 145,           // The sudden change in temperature has delicately shattered t...
    BeyondYourPower = 146,         // It is beyond your power to do that.
    DontKnowHow = 147,             // I don't know how.
    TooFarUp = 148,                // It is too far up for you to reach.
    KilledDwarfCloud = 149,        // You killed a little dwarf.  The body vanishes in a cloud of...
    ShellImpervious = 150,         // The shell is very strong and is impervious to attack.
    CantYouRead = 151,             // What's the matter, can't you read?  Now you'd best start over.
    AxeBouncesDragon = 152,        // The axe bounces harmlessly off the dragon's thick scales.
    DragonNasty = 153,             // The dragon looks rather nasty.  You'd best not try to get by.
    BirdKillsDragon = 154,         // The little bird attacks the green dragon, and in an astound...
    OnWhat = 155,                  // On what?
    BriefMode = 156,               // Okay, from now on i'll only describe a place in full the fi...
    TrollsTough = 157,             // Trolls are close relatives with the rocks and have skin as...
    TrollCatchesAxe = 158,         // The troll deftly catches the axe, examines it carefully, an...
    TrollTakesTreasure = 159,      // The troll catches your treasure and scurries away out of si...
    TrollRefusesCross = 160,       // The troll refuses to let you cross.
    NoWayAcrossChasm = 161,        // There is no longer any way across the chasm.
    BridgeBuckles = 162,           // Just as you reach the other side, the bridge buckles beneat...
    BearScaresTroll = 163,         // The bear lumbers toward the troll, who lets out a startled...
    AxeMissesNearBear = 164,       // The axe misses and lands near the bear where you can't get...
    BareHandsBear = 165,           // With what?  Your bare hands?  Against *his* bear hands??
    BearConfused = 166,            // The bear is confused; he only wants to be your friend.
    BearAlreadyDead = 167,         // For crying out loud, the poor thing is already dead!
    BearWolfsFood = 168,           // The bear eagerly wolfs down your food, after which he seems...
    BearStillChained = 169,        // The bear is still chained to the wall.
    ChainStillLocked = 170,        // The chain is still locked.
    ChainUnlocked = 171,           // The chain is now unlocked.
    ChainLocked = 172,             // The chain is now locked.
    NothingToLockChainTo = 173,    // There is nothing here to which the chain can be locked.
    NothingToEat = 174,            // There is nothing here to eat.
    WantTheHint = 175,             // Do you want the hint?
    HelpWithMaze = 176,            // Do you need help getting out of the maze?
    DropThings = 177,              // You can make the passages look less alike by dropping things.
    ExploreBeyondPlover = 178,     // Are you trying to explore beyond the plover room?
    WayToExplore = 179,            // There is a way to explore that region without having to wor...
    HelpGettingOut = 180,          // Do you need help getting out of here?
    DontGoWest = 181,              // Don't go west.
    TrollNotGluttony = 182,        // Gluttony is not one of the troll's vices.  Avarice, however...
    LampDimWrapUp = 183,           // Your lamp is getting dim.  You'd best start wrapping this u...
    LampOutOfPower = 184,          // Your lamp has run out of power.
    NoPointWandering = 185,        // There's not much point in wandering around out here, and yo...
    RustlingThenPirate = 186,      // There are faint rustling noises from the darkness behind yo...
    LampDimGetBatteries = 187,     // Your lamp is getting dim.  You'd best go back for those bat...
    LampDimReplacing = 188,        // Your lamp is getting dim.  I'm taking the liberty of replac...
    LampDimNoSpares = 189,         // Your lamp is getting dim, and you're out of spare batteries...
    MagazineDwarvish = 190,        // I'm afraid the magazine is written in dwarvish.
    NotPirateMaze = 191,           // "This is not the maze where the pirate leaves his treasure...
    ClueCosts = 192,               // Hmmm, this looks like a clue, which means it'll cost you 10...
    ClueText = 193,                // It says, "there is something strange about this place, such...
    SameAsBefore = 194,            // It says the same thing it did before.
    AfraidDontUnderstand = 195,    // I'm afraid I don't understand.
    CongratsDarkRoom = 196,        // "Congratulations on bringing light into the dark-room!"
    MirrorShatters = 197,          // You strike the mirror a resounding blow, whereupon it shatt...
    VaseHurled = 198,              // You have taken the vase and hurled it delicately to the gro...
    ProdDwarf = 199,               // You prod the nearest dwarf, who wakes up grumpily, takes on...
    IsThisAcceptable = 200,        // Is this acceptable?
    NoSuspendDemo = 201,           // There's no point in suspending a demonstration game.
    Last = 201,
};

// mspeak() -- the wizard's messages.  Most are unreachable here: this port
// dropped the mode that set the cave's opening hours.
enum class Magic : i16 {
    None = 0,
    GreenSmoke = 1,            // A large cloud of green smoke appears in front of you.  It clear...
    WizardsWait = 2,           // Even wizards have to wait longer than that!
    CaveClosed = 3,            // I'm terribly sorry, but colossal cave is closed.  Our hours are:
    WizardsOnly = 4,           // Only wizards are permitted within the cave right now.
    ShortExplorations = 5,     // We do allow visitors to make short explorations during our off...
    OpenHours = 6,             // Colossal cave is open to regular adventurers at the following h...
    VeryWell = 7,              // Very well.
    WizardMayContinue = 8,     // Only a wizard may continue an adventure this soon.
    ResumeLater = 9,           // I suggest you resume your adventure at a later time.
    SeeHours = 10,             // Do you wish to see the hours?
    ChangeHours = 11,          // Do you wish to change the hours?
    NewMagicWord = 12,         // New magic word (null to leave unchanged):
    NewMagicNumber = 13,       // New magic number (null to leave unchanged):
    ChangeMotd = 14,           // Do you wish to change the message of the day?
    SaveVersion = 15,          // Okay.  You can save this version now.
    AreYouAWizard = 16,        // Are you a wizard?
    ProveIt = 17,              // Prove it!  Say the magic word!
    NotWhatIThought = 18,      // That is not what I thought it was.  Do you know what I thought...
    ReallyAWizard = 19,        // Oh dear, you really *are* a wizard!  Sorry to have bothered you...
    Charlatan = 20,            // Foo, you are nothing but a charlatan!
    NewPrimeTime = 21,         // New hours specified by defining "prime time".  Give only the hour
    NewHours = 22,             // New hours for colossal cave:
    LimitLines = 23,           // Limit lines to 70 chars.  End with null line.
    LineTooLong = 24,          // Line too long, retype:
    NoRoomForLine = 25,        // Not enough room for another line.  Ending message here.
    RescheduleHoliday = 26,    // Do you wish to (re)schedule the next holiday?
    HolidayBegin = 27,         // To begin how many days from today?
    HolidayLast = 28,          // To last how many days (zero if no holiday)?
    HolidayName = 29,          // To be called what (up to 20 characters)?
    TooSmall = 30,             // Too small!  Assuming minimum value (45 minutes).
    BreakAndSave = 31,         // Break out of this and save your core-image.
    SaveCoreImage = 32,        // Be sure to save your core-image...
    Last = 32,
};

// clang-format on

// Several sites pick from a run of consecutive messages -- the obituaries, the
// clam and the oyster, the door's hinges.  This is what makes them say so.
constexpr Msg operator+(Msg m, int n)
{
    return Msg(i16(m) + n);
}
