1:1 kw def
1:5 name f
1:6 op (
1:7 name x
1:8 op )
1:9 op :
1:10 newline
2:1 indent
2:5 kw if
2:8 name x
2:9 op :
2:10 newline
3:1 indent
3:9 kw return
3:16 int 1
3:17 newline
4:5 dedent
4:5 kw else
4:9 op :
4:10 newline
5:1 indent
5:9 kw return
5:16 int 2
5:17 newline
7:1 dedent
7:1 dedent
7:1 kw class
7:7 name C
7:8 op :
7:9 newline
11:1 indent
11:5 kw def
11:9 name g
11:10 op (
11:11 name self
11:15 op )
11:16 op :
11:17 newline
12:1 indent
12:9 kw while
12:15 kw True
12:19 op :
12:20 newline
13:1 indent
13:13 kw break
13:18 newline
14:9 dedent
14:9 kw for
14:13 name i
14:15 kw in
14:18 name range
14:23 op (
14:24 int 3
14:25 op )
14:26 op :
14:27 newline
15:1 indent
15:13 kw pass
15:17 newline
16:9 dedent
16:9 kw return
16:16 kw None
16:20 newline
17:1 dedent
17:1 dedent
17:1 endmarker
