get slice(1, 2, 3)
bc
get slice(1, 2, 3)
set slice(4, 5, 6)
bc
set slice(4, 5, 6)
del slice(7, 8, 9)
bc
del slice(7, 8, 9)
slice(4, 5, 6)
get slice(2, 3, 4)
bc
get slice(2, 3, 4)
get slice(slice(2, 3, 4), 5, None)
bc
get slice(slice(2, 3, 4), 5, None)
get slice(1, slice(slice(2, 3, 4), 5, None), None)
bc
get slice(1, slice(slice(2, 3, 4), 5, None), None)
slice(1, slice(slice(2, 3, 4), 5, None), None)
get (slice(1, 2, None), slice(4, 5, None), slice(7, 8, None))
bc
get (slice(1, 2, None), slice(4, 5, None), slice(7, 8, None))
get (1, slice(4, 5, None), slice(7, 8, None), 2)
bc
get (1, slice(4, 5, None), slice(7, 8, None), 2)
get slice(3, 4, None)
bc
get slice(3, 4, None)
get (slice(1, 2, None), slice(3, 4, None), slice(5, 6, None))
bc
get (slice(1, 2, None), slice(3, 4, None), slice(5, 6, None))
True
