Point(x=1, y=2) 3 Point(x=5, y=2) {'x': 1, 'y': 2} ('x', 'y') Point(x=3, y=4)
True True Point(x, y)
[('a', 5), ('b', 2)] 5 0 ['a', 'a', 'a', 'a'] 11
7 0 [('a', 1), ('b', 1), ('c', 1)]
deque([1, 2, 3, 4], maxlen=4) 4 [4, 3, 2, 1]
OrderedDict({'a': 1}) ['b', 'a'] ('b', 2)
defaultdict(<class 'list'>, {'k': [1]}) <class 'list'>
1 3 2 ['a', 'b'] 0
1 yyyy True 1 {'x': 1}
[1, 2, 3] [1, 2, 3, 4] [2, 3]
HELLO el hello! 5
True True True True False True
1 0 True [('a', 1), ('b', 2)] True {'a': 1, 'b': 2}
['a', 'b'] [1, 2]
