Color.RED <Color.GREEN: 2> Color.BLUE Color.RED [<Color.RED: 1>, <Color.GREEN: 2>, <Color.BLUE: 3>] 3 True
RED 1 3 Color True
True False True r
2 True 2 2 1 1
Perm.R|W True False [<Perm.R: 4>, <Perm.W: 2>] Perm.W|X False <Perm.R|W: 6>
a BEE bee
9 is not a valid Color
duplicate values found in <enum 'Dup'>: B -> A
dict_keys(['RED', 'GREEN', 'BLUE']) 0
True (5.97e+24, 6370000.0)
True [<Color.GREEN: 2>]
